firmware-qcom-sa8155p: Package SA8155p ADP firmware files
Linaro/meta-qcom pull request #366
Opened 2021-09-30 11:52 UTC by bhupesh-sharma

Add recipe extracting SA8155p ADP firmware files from
Qualcomm's binary releases and packaging them into proper
binary package.

Signed-off-by: Bhupesh Sharma <bhupesh.sharma@linaro.org>

2021-09-30 12:00 UTC, lumag requested changes

2021-09-30 12:00 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-sa8155p_1.0.bb
> +INHIBIT_DEFAULT_DEPS = "1"
Please use `firmware-qcom.inc`

2021-10-01 02:14 UTC, bhupesh-sharma commented on recipes-bsp/firmware/firmware-qcom-sa8155p_1.0.bb
> +COMPATIBLE_MACHINE = "(sa8155p)"
Ok.

2021-10-01 02:15 UTC, bhupesh-sharma commented on recipes-bsp/firmware/firmware-qcom-sa8155p_1.0.bb
> +        install -m 0444 cdsp*.* ${D}${nonarch_base_libdir}/firmware/qcom/sa8155p
We have .mdt files files only - for cDSP and aDSP. No plan to pil-squach the .mdt file(s) into .mbn ones for the initial sa8155p support.

2021-10-01 02:17 UTC, bhupesh-sharma commented on recipes-bsp/firmware/firmware-qcom-sa8155p_1.0.bb
> +# Provide base URI of 'sa8155p_adp_fw.zip' files here.
Archive is created sa8155p_adp_fw folder provided by QCoM using:

$ zip -r sa8155p_adp_fw.zip sa8155p_adp_fw

2021-10-01 02:17 UTC, bhupesh-sharma commented on recipes-bsp/firmware/firmware-qcom-sa8155p_1.0.bb
> +INHIBIT_DEFAULT_DEPS = "1"
Ok.

2023-04-28 20:08 UTC, closed without merging