linux-yocto: add support for QCM6490 RB3 board
Linaro/meta-qcom pull request #541
Opened 2023-11-14 13:17 UTC by adhudase

Add necessary configuration and kernel changes to the linux-yocto recipe to enable support for Qualcomm QCM6490 RB3 board.

This enables boot to shell on QCM6490 RB3 board with initramfs.

2023-11-14 13:53 UTC, lumag requested changes
I took both -yocto and patch review.
The largest issue is the split. You have submitted a lot of changes in a single chunk. Instead split them into single atomic commits doing just a single item: patch linux-yocto, change machine config, etc.

Second. Please split your 26-patch series into smaller chunks too. You have a mixture of boards support, generic changes, temporary changes, debugging changes, etc.
For example, if you take away the patch 10 (definitely a temporary BSP item), it should not cause any changes to e.g. dma-heap patches.

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-qcm6490.cfg
> +CONFIG_SC_CAMCC_7280=y
=m

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-qcm6490.cfg
> +CONFIG_SC_LPASS_CORECC_7280=y
=m

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-qcm6490.cfg
> +CONFIG_SC_VIDEOCC_7280=y
=m

2023-11-14 13:53 UTC, lumag commented on conf/machine/qcom-armv8a.conf
> +KERNEL_CMDLINE_EXTRA[qcm6490-rb3] ?= "pcie_pme=nomsi earlycon"
- earlycon should not be necessary for the board to boot, so it should be dropped here (it can go into your local.conf)
- what is the reason for pcie_pme=nomsi? I think there was an issue with the ath11k driver, but it was solved ages ago.

2023-11-14 13:53 UTC, lumag commented on conf/machine/qcom-armv8a.conf
> +    qcom/qcm6490-rb3.dtb \
This should be conditional on linux-yocto. This DT is not supported in `linux-linaro-qcomlt`.

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0007-FROMGIT-phy-qcom-qmp-ufs-Add-Phy-Configuration-suppo.patch
> +Signed-off-by: Manish Pandey <quic_mapa@quicinc.com>
- Drop the `Git-commit` and `Git-repo` tags, you have `Upstream-Status` instead
- Drop the empty line betwen the tags, they should come as a single chunk with no interruptions
- Drop the Change-Id tag, there is no Gerrit to track them

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0008-PENDING-arm64-dts-qcom-Remove-voltage-vote-support-f.patch
> ++};
I don't think we can take these two patches w/o discussion at the mailing list. Min and max voltages are required anyway, even if you don't touch the regulators. They provide the sane values for the rest of the regulator subsystem.

Moreover, the regulators were defined in this DT file, so you can change them directly instead of patching them through the `&vreg_l7b_2p9 { };` statement.

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0016-PENDING-arm64-dts-qcom-Add-qcm6490-rb3-support.patch
> ++	model = "Qualcomm Technologies, Inc. QCM6490 RB3";
This is not the board name, isn't it?

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0020-PENDING-arm64-dts-qcm6490-rb3-Remove-voltage-voting-.patch
> +in USB driver.
Ah. I think I now understand your issue. Please change the min and max values to the values that are able to sustain the USB.

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0021-PENDING-clk-qcom-gcc-Enable-the-force-mem-core-for-U.patch
> +transition delays to the recommended values for functional correctness.
The commit message should tell why, not what. In other words it should describe why the change was done, not the contents of the patch. And it anyway should be split into two patches.

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0022-PENDING-arm64-dts-qcm6490-Update-the-protected-clock.patch
> ++			<GCC_WPSS_AHB_BDG_MST_CLK>, <GCC_WPSS_RSCP_CLK>;
Ugh. The `qcm6490-fairphone-fp5` lists less clocks here. Is there any reason for that?

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0004-FROMLIST-arm64-dts-qcom-Add-qcm6490-dts-file.patch
> ++	reg = <0x0 0x8a700000 0x0 0x500000>;
This is not correct. The node name is `memory@8b200000`. So you have to delete the old node and add a new one instead (this applies to other reserved memory nodes).

2023-11-14 13:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0012-FROMLIST-dma-heap-Add-proper-kref-handling-on-dma-bu.patch
> +Patch-mainline: linux-media @ 09/11/23, 02:30
-ENOSUCHTAG

2023-11-14 13:56 UTC, lumag commented
For the patch-related comments. You don't have to fix issues that I pointed out for the patch contents. Please pass them to your kernel team. However please fix the patch formatting issues (tags, etc).

2023-11-14 13:58 UTC, lumag commented on conf/machine/include/qcom-common.inc
> +PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
This chunk is a definiteve no-go. linux-yocto doesn't support any of machines except qcom-armv8a.

2023-11-15 06:24 UTC, adhudase commented on conf/machine/include/qcom-common.inc
> +PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
May I know how are you building linux-yocto for RB5? Thanks

2023-11-15 06:25 UTC, lumag commented on conf/machine/include/qcom-common.inc
> +PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
By setting the `PREFERRED_PROVIDER_virtual/kernel` in the `local.conf`

2023-11-15 06:29 UTC, sbanerjee-quic commented on conf/machine/qcom-armv8a.conf
> +    qcom/qcm6490-rb3.dtb \
Hi @lumag 
How do we share this machine conf for all the existing RBX and new RB3-Gen2

2023-11-15 06:33 UTC, sbanerjee-quic commented on conf/machine/include/qcom-common.inc
> +PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
By when we can set  PREFERRED_PROVIDER_virtual/kernel as linux-yocto? We understood that all boards can be supported on linux-yocto.

2023-11-15 07:01 UTC, lumag commented on conf/machine/include/qcom-common.inc
> +PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
You can set it for the `qcom-armv8a` machine.

2023-11-15 07:04 UTC, lumag commented on conf/machine/qcom-armv8a.conf
> +    qcom/qcm6490-rb3.dtb \
> This should be conditional on linux-yocto

So, I suppose, something like `KERNEL_DEVICETREE:append:pn-linux-yocto` += "qcom/qcom6490-rb3.dtb"`

2023-11-16 07:08 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/0008-PENDING-arm64-dts-qcom-Remove-voltage-vote-support-f.patch
> ++};
>>I don't think we can take these two patches w/o discussion at the mailing list. Min and max voltages are required >>anyway, even if you don't touch the regulators. They provide the sane values for the rest of the regulator subsystem.

UFS 2.x / 3.x have different voltage requirements -- Bootloader dynamically sets the proper voltage based on UFS2.x/3.x
There is a limitation in regulator framework -- where during regulator registration it will set the min voltage specified in DT -- which might over-ride the bootloader set voltage causing UFS failure.
Also, for both of these regulators UFS is the only client on those loads and it does not vote for voltage from it's driver..
in DT bindings as well, we see regulator-min/max DT properties are optional properties.
hence we have removed this properties to fix the above issue.

>>Moreover, the regulators were defined in this DT file, so you can change them directly instead of patching them >>through the &vreg_l7b_2p9 { }; statement.

We''ll update accordingly.

2023-11-16 07:10 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/0020-PENDING-arm64-dts-qcm6490-rb3-Remove-voltage-voting-.patch
> +in USB driver.
yes, we'll update min and max values.

2023-11-16 07:11 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0008-PENDING-arm64-dts-qcom-Remove-voltage-vote-support-f.patch
> ++};
> > > I don't think we can take these two patches w/o discussion at the mailing list. Min and max voltages are required >>anyway, even if you don't touch the regulators. They provide the sane values for the rest of the regulator subsystem.
> 
> UFS 2.x / 3.x have different voltage requirements -- Bootloader dynamically sets the proper voltage based on UFS2.x/3.x There is a limitation in regulator framework -- where during regulator registration it will set the min voltage specified in DT -- which might over-ride the bootloader set voltage causing UFS failure. Also, for both of these regulators UFS is the only client on those loads and it does not vote for voltage from it's driver.. in DT bindings as well, we see regulator-min/max DT properties are optional properties. hence we have removed this properties to fix the above issue.

Then the UFS driver should set correct values during the probe.

2023-11-16 15:17 UTC, lumag requested changes

2023-11-16 15:17 UTC, lumag commented on conf/machine/include/qcom-common.inc
> +PREFERRED_PROVIDER_virtual/kernel ?= "linux-linaro-qcomlt"
Clean branch, please, without merges and reverts.

2023-11-16 15:17 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0006-PENDING-dt-bindings-arm-qcom-Add-QCM6490-RB3-board.patch
> +Subject: [PATCH 06/26] PENDING: dt-bindings: arm: qcom: Add QCM6490 RB3 board
This doesn't look as a separate series. It starts with the "PATCH 06/26". Separate series start with "PATCH 01"

2023-11-16 15:19 UTC, lumag commented
- Drop the merge and revert, please. We do not have a requirement that you start at the top of the tree.
- Split the patchset into separate series. I literally mean that. Separate subdirs, that will probably make life easier (and will also simplify handling of the patches). The patches 01-26 do not look like a separate series.

2023-11-17 06:31 UTC, adhudase commented
Sory, this seems getting dirty. Can we close this request and create new one? Thanks

2023-11-17 11:29 UTC, lumag requested changes
Please move series to subdirs to ease maintenance.

Other than that, few minor comments left.

2023-11-17 11:29 UTC, lumag commented on conf/machine/qcom-armv8a.conf
>  # Support for dragonboard{410, 820, 845}c, rb5
?=, please. Allow users to override this value.

2023-11-17 11:29 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-qcm6490.cfg
> +CONFIG_SC_GPUCC_7280=y
GCC?

2023-11-17 11:29 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0001-FROMLIST-arm64-dts-qcom-Use-QCOM_SCM_VMID-defines-fo.patch
> + for qcom,vmid
This is still /26. So the series looks incomplete now.

2023-11-17 13:34 UTC, adhudase commented on conf/machine/qcom-armv8a.conf
>  # Support for dragonboard{410, 820, 845}c, rb5
sure

2023-11-17 13:41 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-qcm6490.cfg
> +CONFIG_SC_GPUCC_7280=y
All of the above selects GCC. 
e.g.
config SC_DISPCC_7280
        ...
        select SC_GCC_7280

2023-11-17 13:41 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/0001-FROMLIST-arm64-dts-qcom-Use-QCOM_SCM_VMID-defines-fo.patch
> + for qcom,vmid
ah! sorry, will correct and re-post.

2023-11-17 13:43 UTC, adhudase commented
By subdirs, do you mean something like devicetree, bindings, drivers etc.? or something like - boards support, generic changes, temporary changes, debugging changes, etc. you mentioned earlier?

2023-11-17 14:07 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-qcm6490.cfg
> +CONFIG_SC_GPUCC_7280=y
I'd prefer to be explicit here. In-ketrnel dependencies can change.

2023-11-17 14:08 UTC, lumag commented
> By subdirs, do you mean something like devicetree, bindings, drivers etc.? or something like - boards support, generic changes, temporary changes, debugging changes, etc. you mentioned earlier?

Yes. So that each group of patches is visually distinct.

2023-11-18 08:12 UTC, adhudase commented on conf/machine/qcom-armv8a.conf
>  # Support for dragonboard{410, 820, 845}c, rb5
just observed that, with ?=, its going back to linaro-qcomlt

2023-11-18 11:25 UTC, adhudase commented
I've created these four subdirs - 
common-platform, 
idp, rb3gen2,
generic-kernel-6.5

if this looks okay, I can push the patches.

2023-11-19 17:50 UTC, lumag commented
> generic-kernel-6.5



> common-platform,
> idp, rb3gen2,
> generic-kernel-6.5

Well, `generic-kernel-6.5` defintely doesn't look ok. Upgrading to 6.6 would cause unnecessary renames.
I'd propose something simpler:

- generic-drivers
- qcm6490-drivers
- qcm6490-dtsi
- qcm6490-board-dts
- hacks (all temporary and workaround patches go to this subdir).

2023-11-19 18:12 UTC, lumag commented on conf/machine/qcom-armv8a.conf
>  # Support for dragonboard{410, 820, 845}c, rb5
So, you need to shuffle things around.

2023-11-19 18:13 UTC, lumag commented on conf/machine/qcom-armv8a.conf
> +    qcom/qcm6490-rb3.dtb \
As a second thought, please keep this conditional for now, until we fully phase out linux-linaro-qcomlt kernel recipe.

2023-11-19 18:15 UTC, lumag commented on recipes-kernel/linux/linux-yocto/0001-FROMLIST-dma-heap-Add-proper-kref-handling-on-dma-bu.patch
> +[Yong: Just add comment for "minor" and "refcount"]
JFYI: it should be `added`. Also such comments usually go before S-o-b.

2023-11-20 13:17 UTC, lumag requested changes

2023-11-20 13:17 UTC, lumag commented on recipes-kernel/linux/linux-yocto_6.5.bbappend
> +FILESEXTRAPATHS:prepend:qcom := "${THISDIR}/${PN}/generic-drivers:"
Please keep subdirs as a part of the patch name.

2023-11-20 18:33 UTC, lumag requested changes
Now that the series are sorted out, coud you pelase reorder into the sensible order:

- generic-drivers
- qcm6490-drivers
- qcm6490-dtsi
- qcm6490-board-dts
- hacks

2023-11-21 04:44 UTC, hashim-shiraz commented
> Now that the series are sorted out, coud you pelase reorder into the sensible order:
> 
> * generic-drivers
> * qcm6490-drivers
> * qcm6490-dtsi
> * qcm6490-board-dts
> * hacks

Can we have an alternate name for hacks which I guess would raise questions. How about workarounds (or any other name) ?

2023-11-21 09:05 UTC, lumag commented
> Can we have an alternate name for hacks which I guess would raise questions. How about workarounds (or any other name) ?

Sure, why not.

2023-11-21 12:04 UTC, lumag approved these changes

2023-11-21 12:18 UTC, merged