Bump revisions for a few support projects
Linaro/meta-qcom pull request #544
Opened 2023-11-15 12:22 UTC by quic-vkraleti

Bumped SRCREV for fastrpc, qrtr, rmtfs tqftpserv and skales recipes to pick latest commits from respective projects and build.

2023-11-15 12:40 UTC, lumag requested changes

2023-11-15 12:40 UTC, lumag commented on recipes-support/fastrpc/fastrpc_git.bb
>  SYSTEMD_AUTO_ENABLE:${PN}-systemd = "disable"
```
Parsing recipes...ERROR: ../meta-qcom/recipes-support/fastrpc/fastrpc_git.bb: Unable to get checksum for fastrpc SRC_URI entry sdsprpcd.service: file could not be found
```

2023-11-15 12:41 UTC, lumag commented
Also, could you please take a look at the surrounding commits and follow the existing  subject style.

2023-11-15 12:57 UTC, quic-vkraleti commented on recipes-support/fastrpc/fastrpc_git.bb
>  SYSTEMD_AUTO_ENABLE:${PN}-systemd = "disable"
Adding sdsprpc.service under files meta-qcom/recipes-support/fastrpc/fastrpc folder

2023-11-15 13:02 UTC, quic-vkraleti commented on recipes-support/qrtr/qrtr_git.bb
> +EXTRA_OEMAKE = "prefix=${prefix} bindir=${bindir} libdir=${libdir} includedir=${includedir} LDFLAGS='${LDFLAGS}'"
Removed both.

2023-11-15 13:13 UTC, quic-vkraleti commented
I am not able to cleanly update commits. I am taking down this request and 'll submit another one.

2023-11-15 13:14 UTC, lumag commented
@quic-vkraleti No. Please don't do that. Reopening.

2023-11-15 13:17 UTC, lumag commented
Please find a good Git manual and study how to work with commits. Opening new PR for the same featureset means killing previous review and conversations, thus it is frowned upon.

2023-11-15 13:30 UTC, lumag commented
No need to merge master. It's done automatically during the merge. Please remove the merge commit.

2023-11-15 15:03 UTC, lumag commented
Please fix commit sujects to follow 'name: description' instead of 'recipes-foo: bar do something'.

2023-11-16 12:14 UTC, lumag approved these changes

2023-11-16 12:14 UTC, merged