read android device serial number from sysfs node
Linaro/meta-qcom pull request #547
Opened 2023-11-17 14:10 UTC by vishwasudupa

read android serial number value from sysfs node
instead of kernel command line. Upstream boot managers
e.g., systemd-boot does not populate kernel command line
with parameter androidboot.serialno.

Reading serial number from sysfs node
/sys/devices/soc0/serial_number generalizes the approach
and makes it independent of bootloader that loads kernel.

2023-11-17 14:18 UTC, lumag commented
Fix commit messages, please.

2023-11-17 14:49 UTC, lumag commented
Still not fully correct. Please take a note on the difference between your text and previous commit messages.

2023-11-17 15:09 UTC, lumag commented
Also, what is `Linux Build Service Account <lnxbuild@localhost>`, that has committed this patch?

2023-11-17 15:14 UTC, lumag commented on dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/qcom/android-gadget-setup.machine
> +androidserial="$(printf "%x" "$(cat /sys/devices/soc0/serial_number)")"
I checked both ABL and LK sources. The serial number is generated basing on the storage data rather than the SoC serial number. Could you please implement the same approach?

2023-11-17 16:05 UTC, vishwasudupa commented
> Also, what is `Linux Build Service Account <lnxbuild@localhost>`, that has committed this patch?

Corrected committer-id.

2023-11-19 18:09 UTC, lumag approved these changes
1. Please keep UFS devices working.

2023-11-19 18:11 UTC, lumag requested changes
1. Please keep UFS devices working.
2. Please make this more robust by checking that the the MMC device exists and that it is actually an eMMC device.

2023-11-19 18:19 UTC, sbanerjee-quic commented on dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/qcom/android-gadget-setup.machine
> +androidserial="$(sed 's/0x//' /sys/class/mmc_host/mmc0/mmc0:0001/serial)"
Hi @lumag 

For the RB5, RB3 UFS devices you are using in which sysfs node you see the adb serial numbers matching?

2023-11-19 18:34 UTC, lumag commented on dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/qcom/android-gadget-setup.machine
> +androidserial="$(sed 's/0x//' /sys/class/mmc_host/mmc0/mmc0:0001/serial)"
According to what I see in ABL sources, the serial number of the UFS-based boards is a CRC-32 of the UFS serial no.
For the reference, the RB5 that I have at hand:
```
# udevadm info /dev/sda | grep SERIAL
E: ID_SERIAL=2SAMSUNG
E: ID_SERIAL_SHORT=SAMSUNG
E: ID_SCSI_SERIAL=414b8c053f19
root@qcom-armv8a:~# xargs -n 1 < /proc/cmdline  | grep serial
androidboot.serialno=9105fd32
```

2023-11-19 18:35 UTC, lumag commented on dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/qcom/android-gadget-setup.machine
> +androidserial="$(sed 's/0x//' /sys/class/mmc_host/mmc0/mmc0:0001/serial)"
Relevant piece from ABL:

```c
  Status =
      gBS->HandleProtocol (HandleInfoList[0].Handle,
                           &gEfiMemCardInfoProtocolGuid, (VOID **)&CardInfo);
  if (Status != EFI_SUCCESS) {
    DEBUG ((EFI_D_ERROR, "Error locating MemCardInfoProtocol:%x\n", Status));
    return Status;
  }

  if (CardInfo->GetCardInfo (CardInfo, &CardInfoData) == EFI_SUCCESS) {
    if (Type == UFS) {
      Status = gBS->CalculateCrc32 (CardInfoData.product_serial_num,
                                    CardInfoData.serial_num_len, &SerialNo);
      if (Status != EFI_SUCCESS) {
        DEBUG ((EFI_D_ERROR,
                "Error calculating Crc of the unicode serial number: %x\n",
                Status));
        return Status;
      }
      AsciiSPrint (StrSerialNum, Len, "%x", SerialNo);
    } else {
      AsciiSPrint (StrSerialNum, Len, "%x",
                   *(UINT32 *)CardInfoData.product_serial_num);
    }
```

2023-11-21 15:18 UTC, vishwasudupa commented
Below pr solves the issue 
https://github.com/Linaro/meta-qcom/pull/553

2024-12-03 07:33 UTC, vishwasudupa commented
no longer needed

2024-12-03 07:33 UTC, closed without merging