Efi boot support
Linaro/meta-qcom pull request #548
Opened 2023-11-18 11:09 UTC by quic-vkraleti

To support systemd-boot as a boot manager, need to create an esp.bin with uki, uefi stub and other essential packaged into it. 
This is achieved in below patches.
1. Extend systemd-boot recipe through a bbappend to provide Ukify tool.
2. Add linux-qcom-efiimg bbclass to generate uki and in turn pack this uki into esp.bin
3. Inherit linux-qcom-efiimg bbclass in linux-yocto & linux-linaro recipes to generate esp.bin

2023-11-19 18:08 UTC, lumag requested changes
Comments inline. Also please take care to fix CI breakage on 32-bit platforms.

2023-11-19 18:08 UTC, lumag commented on classes/linux-qcom-efiimg.bbclass
> +    fi
If this is a mkfs.vfat bug, it should be handled as a patch against dosfstools.

2023-11-19 18:08 UTC, lumag commented on classes/linux-qcom-efiimg.bbclass
> +    ukify_cmd = d.getVar('RECIPE_SYSROOT') +"/" + d.getVar('USRBINPATH') +"/ukify build"
You shouldn't need to generate a path to `ukify` if you are doing things right.

2023-11-19 18:08 UTC, lumag commented on classes/linux-qcom-efiimg.bbclass
> +#   - UEFI default dtb
Two steps, two different classes (or two recipes).

2023-11-19 22:14 UTC, lumag commented
Also, did you consider using the wic's bootimg-efi plugin?

2023-11-19 22:19 UTC, lumag commented
Also see https://lore.kernel.org/all/20230901233231.1109712-1-michelle.linto91@gmail.com/T/.

2023-11-20 09:37 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot_%.bbappend
> +    install -m 0755 ${S}/src/ukify/ukify.py ${SYSROOT_DESTDIR}${bindir}/ukify
First, I tired the same. Compiling systemd-boot native is not trivial. Recipe need to be tweaked a lot to fit in both -native & -target compilations. Moreover, to build UKI, don't need any of the compiled artifacts except Ukify tool. Which is a script used as is from sources of systemd-boot. Also, from the comments in https://lore.kernel.org/all/20230901233231.1109712-1-michelle.linto91@gmail.com/T/.  I could see community is not preferring to have a -native recipe for systemd.  With all these in mind, felt copying ukify tool to staging directory is much simpler way to consume.

2023-11-20 09:47 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot_%.bbappend
> +    install ${B}/src/boot/efi/systemd-boot*.efi ${SYSROOT_DESTDIR}${bindir}/${SYSTEMD_BOOT_IMAGE}
At present boot.img is generated as soon as "bitbake virtual/kernel" is complete. To achieve the same even with esp.bin generation,  if efi.stub & systemd-boot.efi are picked from DEPLOYDIR, kernel compilation has to wait till deploy directory is populated with these. Moreover as ukify script is picked from STAGING, felt coping even these files into staging would acceptable.

2023-11-20 09:48 UTC, quic-vkraleti commented on classes/linux-qcom-efiimg.bbclass
> +    build_fat_img ${EFIIMGDIR} ${EFIIMG_DEPLOYDIR}/${EFIIMG}
Sure, I'll inherit image-live class to generate esp.bin

2023-11-20 09:52 UTC, lumag commented on classes/linux-qcom-efiimg.bbclass
> +    build_fat_img ${EFIIMGDIR} ${EFIIMG_DEPLOYDIR}/${EFIIMG}
You even don't need image-live. You only need a separate image recipe, which pulls in the uki kernel and some additional data.

2023-11-20 09:52 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot_%.bbappend
> +    install -m 0755 ${S}/src/ukify/ukify.py ${SYSROOT_DESTDIR}${bindir}/ukify
Should I make this native package as part of a new recipe instead of systemd-boot-native, by using exactly same code base?

2023-11-20 09:53 UTC, lumag commented on recipes-core/systemd/systemd-boot_%.bbappend
> +    install ${B}/src/boot/efi/systemd-boot*.efi ${SYSROOT_DESTDIR}${bindir}/${SYSTEMD_BOOT_IMAGE}
It is fine to generate uki image during `bitbake virtual/kernel`. However the esp.bin is a separate story. It might contain different images. I might contain other files, e.g. UEFI shell.

2023-11-20 09:54 UTC, lumag commented on recipes-core/systemd/systemd-boot_%.bbappend
> +    install -m 0755 ${S}/src/ukify/ukify.py ${SYSROOT_DESTDIR}${bindir}/ukify
systemd-boot-native seems like a right solution to me

2023-11-20 10:33 UTC, quic-vkraleti commented
Build error on arm7 is due to a bug in systemd code base. Faced same issue even without any of the above changes.  https://github.com/systemd/systemd/commit/cecbb162a3134b43d2ca160e13198c73ff34c3ef fixes it. I'll pull this change a .patch for now to mitigate.

2023-11-20 10:35 UTC, quic-vkraleti commented on classes/linux-qcom-efiimg.bbclass
> +#   - UEFI default dtb
Sure.

2023-11-20 12:43 UTC, lumag commented
> Also see https://lore.kernel.org/all/20230901233231.1109712-1-michelle.linto91@gmail.com/T/.

After internal discussion, I think the uki.bbclass is a way to go.

2023-11-22 14:15 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot_%.bbappend
> +    install ${B}/src/boot/efi/systemd-boot*.efi ${SYSROOT_DESTDIR}${bindir}/${SYSTEMD_BOOT_IMAGE}
Added uki.bbclass to build UKI as part of kernel compilation.

2023-11-22 14:25 UTC, quic-vkraleti commented on classes/linux-qcom-efiimg.bbclass
> +    fi
Even image-live.bbclass is handling it in the same way.

2023-11-22 14:29 UTC, lumag commented on classes/linux-qcom-efiimg.bbclass
> +    fi
It doesn't mean that we have to copy it.

2023-11-22 14:42 UTC, quic-vkraleti commented on classes/linux-qcom-efiimg.bbclass
> +    fi
Noted, I'll work on it and submit a patch to mtools. But not as part of this pull request.

2023-11-22 14:47 UTC, lumag commented on recipes-core/systemd/systemd-boot_%.bbappend
> +SRC_URI += " \
:qcom

2023-11-22 14:48 UTC, lumag commented on recipes-core/systemd/systemd-boot-native_254.4.bb
> +SRC_URI = "git://github.com/systemd/systemd-stable.git;protocol=https;branch=${SRCBRANCH}"
Can we please use BBCLASSEXTEND instead?

2023-11-22 14:53 UTC, lumag commented on classes/image-vfat.bbclass
> +}
Is there any reason for using this approach instead of installing all the files via usual packages?

2023-11-22 15:00 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot_%.bbappend
> +SRC_URI += " \
I'll change SRC_URI to SRC_URI:qcom. I don't find anyone submitting this to Oe-Core. 'll do that as well.

2023-11-22 15:06 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot-native_254.4.bb
> +SRC_URI = "git://github.com/systemd/systemd-stable.git;protocol=https;branch=${SRCBRANCH}"
I tired that but it is mandating changes for most of the major tasks like, do_configure, do_compile, do_install. So felt it is much simpler to have systemd-boot-native.bb instead. Take a look attachment to know the changes I need to make.
[systemd-boot_254.4.bb](https://github.com/Linaro/meta-qcom/files/13441149/systemd-boot_254.4.bb.txt)

2023-11-22 15:18 UTC, quic-vkraleti commented on classes/image-vfat.bbclass
> +}
Creating FAT filesystem images is slightly different from other formats. Unlike ext2/3/4, one can't place all files under a directory and use mkfs to get the image. FAT requires below steps 
1. Preallocate required space (using tools like dd). 
2. Format it using mkdosfs utility. 
3. Mount it and place content. Or copy content using mcopy.

Above bbclass is just doing the same.

2023-11-22 18:05 UTC, lumag commented on recipes-core/systemd/systemd-boot_%.bbappend
> +SRC_URI += " \
Please do that now. There is no need to have generic patches in the BSP layer.

2023-11-22 18:09 UTC, lumag commented on classes/image-vfat.bbclass
> +}
No. Existing framework already has `IMAGE_FSTYPES = "vfat"`. Please stick to it unless there is a good reason to implement it by hand.

2023-11-22 18:10 UTC, lumag commented on recipes-core/systemd/systemd-boot-native_254.4.bb
> +SRC_URI = "git://github.com/systemd/systemd-stable.git;protocol=https;branch=${SRCBRANCH}"
This is fine from my POV. Another option might be to make meson inheritance conditional on the native build.
I do not want to see systemd-boot and systemd-boot-native to deviate.
And anyway, this should go to OE-core instead of meta-qcom.

2023-11-22 18:39 UTC, lumag commented
And by the play, please take a look at resolving the build error reported by the CI (for nodistro builds):

> linux-yocto PROVIDES virtual/kernel but was skipped: missing required distro feature 'systemd' (not in DISTRO_FEATURES)

Thank you.

2023-11-23 08:30 UTC, quic-vkraleti commented on classes/image-vfat.bbclass
> +}
I tired that but with the generated images, couldn't boot device. Probably 'll go ahead with "wic" implementation as  I see bootimg-efi plugin in wic. If you are fine, let this bbclass in for now. Later with "wic" implementaiton i'll drop it. If this is something that bothers, I'l drop this commit and will just have UKI support for now.

2023-11-23 08:32 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot-native_254.4.bb
> +SRC_URI = "git://github.com/systemd/systemd-stable.git;protocol=https;branch=${SRCBRANCH}"
I dropped -native.bb file and folded required changes into systemd-boot_%.bbappend. I'll submit a change to OE-Core also to get Ukify tool out on the host.

2023-11-23 08:45 UTC, lumag commented on recipes-core/systemd/systemd-boot-native_254.4.bb
> +SRC_URI = "git://github.com/systemd/systemd-stable.git;protocol=https;branch=${SRCBRANCH}"
Pease send these patches to OE-core. I'l wait for their decision.

2023-11-23 08:53 UTC, lumag commented on classes/image-vfat.bbclass
> +}
What was the issue? Coud you compare the generated images?

2023-11-23 22:13 UTC, lumag commented
@quic-vkraleti Please send the systemd patches to the oe-core list.

2023-11-27 10:11 UTC, quic-vkraleti commented on classes/image-vfat.bbclass
> +}
Previously I tried on Kirkstone. There is no support for vfat in Krikstone's image-types.bbclass. This support is added in master branch with [440fa508d362b8a449beb1b82dd999e980b753b7] (https://patchwork.yoctoproject.org/project/oe-core/patch/20230818163244.1733763-1-JPEWhacker@gmail.com/) I guess we are good now. I'll drop the custom logic to pack vfat.

2023-11-27 12:44 UTC, lumag requested changes

2023-11-27 13:08 UTC, lumag commented on recipes-core/systemd/systemd-boot_%.bbappend
> +DEPENDS:class-native = " python3-pefile-native"
Should we change this RDEPENDS to RRECOMMENDS instead?

2023-11-28 09:24 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot_%.bbappend
> +DEPENDS:class-native = " python3-pefile-native"
Changed to RDEPENDS.

2023-11-28 09:24 UTC, quic-vkraleti commented on recipes-kernel/linux/linux-yocto_%.bbappend
> -
Done

2023-11-28 09:24 UTC, quic-vkraleti commented on recipes-kernel/linux/linux-linaro-qcom.inc
> -inherit linux-qcom-bootimg
Done

2023-11-28 09:27 UTC, quic-vkraleti commented on recipes-kernel/images/esp-qcom-image.bb
> +UEFI_DEFAULT_DTB ?= ""
changes made to populate both idp & rb3 dtb files.

2023-11-28 09:27 UTC, quic-vkraleti commented on recipes-kernel/images/esp-qcom-image.bb
> +    build_fat_img ${EFIIMGDIR} ${EFIIMG}
Generating vaft image using do_image_vfat task image_fstypes.bblcass. I needed to tinker the rootfs a bit to get appropriate directory structure UEFI is looking for.

2023-11-28 09:28 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    build_fat_img ${EFIIMGDIR} ${EFIIMG}
Yes, please.

2023-11-28 09:44 UTC, lumag requested changes

2023-11-28 09:44 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    rm -rf boot
If you set `EFI_PREFIX` to the empty string, you will not need this hack.

2023-11-28 09:44 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    rm -rf `ls -d ${IMAGE_ROOTFS}/* | grep -v boot`
No. The point of using existing mechanism is to allow adding more files to the ESP partition depending on the additional requirements.

2023-11-28 09:44 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    install -m 0644 ${DEPLOY_DIR_IMAGE}/linux-${MACHINE}.efi boot/EFI/Linux/
Override KERNEL_IMAGEDEST and use the kernel package instead. You have to change kernel.bbclass to allow overriding the KERNEL_IMAGEDEST for the particular image type. This way the UKI image gets installed to `/`,  all other files go to the proper `/boot` location.

2023-11-28 09:44 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
Why do we need them in the first place? I think the goal is to pass DTB files from the bootloader, so that the ESP doesn't contain DTB files at all.

2023-11-28 09:46 UTC, quic-vkraleti commented on recipes-kernel/images/esp-qcom-image.bb
> +    rm -rf boot
Got it. Will do.

2023-11-28 09:50 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +UEFI_DEFAULT_DTB ?= ""
Adding more DTB doesn't disturb other boards. However I'm more interested in why do you need these DTB in the first place.

2023-11-28 10:20 UTC, quic-vkraleti commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
systemd-boot completely relies on the EFI environment to find a good devicetree.  It can't mange dtb on it's own. Rather it can only replace an existing devicetree in the corresponding EFI configuration table with the one embedded in the ".dtb" section.  [1] 

DTB files at root of ESP serves two purposes
 1. Provides a default dtb in EFI environment for systemd-boot to override.
 2. They serve as a fallback in case dtb in UKI can't be loaded by systemd-boot.

[1] https://manpages.debian.org/experimental/systemd-boot-efi/linuxx64.efi.stub.7.en.html 
"If a DeviceTree is embedded in the ".dtb" section, it replaces an existing DeviceTree in the corresponding EFI configuration table. systemd-stub will ask the firmware via the "EFI_DT_FIXUP_PROTOCOL" for hardware specific fixups to the DeviceTree."

2023-11-28 10:34 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
`However, EBBR does require the system description to be supplied by the platform, not the OS.`, this is a quote from EBBR 2.1.0 spec. If we want for this platform to be compliant with the SystemReady IR (and thus EBBR), the DTB must be provided by the firmware (XBL).

2023-11-28 10:34 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
Thus I expect that the board must be able to boot without any additional DTB files in the ESP partition.

2023-11-28 10:38 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
I can accept this chunk if:
- it comes in a separate commit
- it is clearly documented as a temporal measure to be reverted later, ideally with the estimated date.
- it uses `KERNEL_DEVICETREE` variable instead of adding new one for the DTB list.

2023-11-28 10:59 UTC, hashim-shiraz commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
> Thus I expect that the board must be able to boot without any additional DTB files in the ESP partition.

When UKI doesn't have dtb, firmware (uefi) is picking valid dtb from ESP partition. Does that violate the spec ?
It is still compliant since uefi is the one that is selecting dtb and installing in this case, no ?

Or placing dtbs in ESP partition violates ? I don't know if spec enumerates how the dtb has to be provisioned in such cases (outside UKI).

2023-11-28 11:02 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
@hashim-shiraz This way the DT is still supplied by the OS. It is the operating system, who provides the ESP partition contents. For example, consider the SystemReady ACS. It will not provide the DT in the ESP, so the UEFI will not be able to find one.

2023-11-28 11:29 UTC, calebccff commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
sd-boot now supports loading the DTB all by itself: https://github.com/systemd/systemd/pull/29749

> Provides a default dtb in EFI environment for systemd-boot to override.
...
> When UKI doesn't have dtb, firmware (uefi) is picking valid dtb from ESP partition

This is wrong. The DTB should be embedded in the firmware or loaded from some other "hidden" partition. Loading the DTB from the ESP is fine, but it must be optional as Dmitry said.

> If a DeviceTree is embedded in the ".dtb" section

This refers to embedding the DTB directly inside the sd-boot EFI binary, this would make the UKI image board-specific (as it would override the DTB provided by the firmware). Is this really your intention?

2023-11-28 11:53 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    install -m 0644 ${DEPLOY_DIR_IMAGE}/linux-${MACHINE}.efi boot/EFI/Linux/
... Alternatively you can make UKI kernel go to the `${EFI_PREFIX}` instead of `KERNEL_IMAGEDEST`, as it is a special kind of the image. Probably it is up to the review at the oe-core ML.

2023-11-28 12:18 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
If I remember correctly, one of the goals was to shift towards SystemReady IR and thus supporing generic kernel images.  Is that still the plan? Having a board-specific UKI mostly defeats the idea of using UEFI and systemd-boot.

2023-11-28 12:36 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    done
We are really puzzled here, because with the board-specific UKI basically there is no need to go through all depths of UEFI and sd-boot support. You can continue using ABL. My opinion is that the DT should be provided firmware from one of partitions and the kernel image should be completely generic. Maybe I misunderstand you.

I noticed that uki.bbclass forces first dtb into the UKI. I have commented on the mailing list. We should drop that clause. First DTB is `apq8016-sbc.dtb`, which means nothing for other boards we support.

2023-12-01 13:19 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    for DTB in ${KERNEL_DEVICETREE}; do
Set `KERNEL_DTBDEST` to `EFIDTBDIR` and install the `kernel-devicetree` instead?

2023-12-01 16:07 UTC, quic-vkraleti commented on recipes-kernel/images/esp-qcom-image.bb
> +    install -m 0644 ${DEPLOY_DIR_IMAGE}/linux-${MACHINE}.efi ${IMAGE_ROOTFS}${EFILINUXDIR}
ok, I'll update uki.bbclass to create a package instead of deploying into DEPLOY_DIR_IMAGE.

2023-12-01 16:07 UTC, quic-vkraleti commented on recipes-kernel/images/esp-qcom-image.bb
> +LINGUAS_INSTALL = ""
After converting devicetree & linux.efi into packages, 'll set KERNEL_DEPLOY_DEPEND to empty.

2023-12-01 16:08 UTC, quic-vkraleti commented on recipes-kernel/images/esp-qcom-image.bb
> +    for DTB in ${KERNEL_DEVICETREE}; do
I tired but found an issue in linux-qcom-boot.img. I'll address it first and then fix this.

2023-12-01 21:09 UTC, lumag commented
@quic-vkraleti after these refactorings the ESP recipe together with the EFI_* configuration starts to look more and more like a distro feature. Maybe we repurpose it to the distro layer? (Again, maybe later, not now, if you don't have a distro layer yet).

2023-12-01 21:09 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +EFIDTBDIR ?= "${EFI_PREFIX}/dtb"
Sure

2023-12-04 12:01 UTC, lumag commented on classes/linux-qcom-bootimg.bbclass
> +addtask qcom_img_deploy after do_populate_sysroot do_packagedata do_bundle_initramfs before do_deploy
Separate commit too.
Each logical set of changes should go to a separate commit. This is a rule of thumb.

2023-12-04 12:09 UTC, lumag requested changes
The meson fix was merged to oe-core, please drop it.

I think that changes to qcom-common.inc and the esp-image belong to the distro layer. They describe distro-specific solutions, which might change from distro to distro. Consider e.g. Yoe or poky deciding to use grub. This decision will conflict with the qcom-common changes / setup. Please move these chunks to your distro instead.

With these changes done I will merge this PR.

2023-12-04 13:00 UTC, vkraleti commented
> The meson fix was merged to oe-core, please drop it.
> 
> I think that changes to qcom-common.inc and the esp-image belong to the distro layer. They describe distro-specific solutions, which might change from distro to distro. Consider e.g. Yoe or poky deciding to use grub. This decision will conflict with the qcom-common changes / setup. Please move these chunks to your distro instead.
> 
> With these changes done I will merge this PR.

I haven't seen Poky recommending any bootloader as such. As I understand, bootloader is a choice of MACHINE but not DISTRO. I found "efi" in https://docs.yoctoproject.org/ref-manual/features.html#machine-features list.

We expect device to boot even for "nodistro" configurations. This won't be possible if esp is generated as part of distro layer. To draw parallels with the boot.img, today boot.img is in meta-qcom along with kernel recipe, I think esp.bin should also follow the same.

2023-12-05 12:29 UTC, lumag commented
I'm going to merge this now.

- Please _work_ with upstream to get systemd-boot-native into the oe-core. I want to get it dropped from this layer before the end of the year. This might require discussions on the mailing list, not the send-and-forget approach.
- Please follow the upstream developments on the UKI support.
- I still have impression that ESP image should be moved into the distro layer. The whole set of `EFI_*` variables look like distro-level decisions. I have asked one of my colleagues for his opinion.

2023-12-05 12:29 UTC, merged

2023-12-05 12:52 UTC, mikkorapeli-linaro commented on classes/uki.bbclass
> +
REQUIRED_DISTRO_FEATURES += "usrmerge systemd"
inherit features_check
?

2023-12-05 12:53 UTC, lumag commented on classes/uki.bbclass
> +
systemd should not be required for systemd-boot (or for UKI).

2023-12-05 13:02 UTC, mikkorapeli-linaro commented on classes/uki.bbclass
> +do_install[postfuncs] += "do_uki"
I'm leaning towareds adding the do_uki() task to
addtask uki after do_rootfs before do_image_complete do_image_wic
This way sstate cache has the files. Maybe they are cached also with your approach but I'm not sure. Worth a comment in commit message, and of course followup if upstream poky applys a similar class.

2023-12-05 13:03 UTC, lumag commented on classes/uki.bbclass
> +do_install[postfuncs] += "do_uki"
I hope that we get uki.bbclass in oe-core.

2023-12-05 13:05 UTC, vkraleti commented
> I'm going to merge this now.
> 
> * Please _work_ with upstream to get systemd-boot-native into the oe-core. I want to get it dropped from this layer before the end of the year. This might require discussions on the mailing list, not the send-and-forget approach.
> * Please follow the upstream developments on the UKI support.
> * I still have impression that ESP image should be moved into the distro layer. The whole set of `EFI_*` variables look like distro-level decisions. I have asked one of my colleagues for his opinion.

Thanks for the support. I'll continue working with oe-core to upstream systemd-boot-native.

2023-12-05 13:08 UTC, quic-vkraleti commented on classes/uki.bbclass
> +    deploy_dir_image = d.getVar('DEPLOY_DIR_IMAGE')
This is to read from DEPLOY_DIR not to write into it. I couldn't find any better place to get ramdisk from.

2023-12-05 13:17 UTC, mikkorapeli-linaro commented on classes/uki.bbclass
> +do_install[postfuncs] += "do_uki"
Yep, I'm also using an uki.bbclass derived from the upstream submitted proposal with some fixes/changes on top for secure boot (sbsign-native) and dm-verity, but it's trickty to get all the pieces together. For example had to split wic image creation from uki and dm-verity generation recipes since the order of functions/tasks was not possible to set correctly. WIP still on my side too.

2023-12-05 13:29 UTC, lumag commented
@mikkorapeli-linaro thank you for your comments!