Add firmware package support for RB3Gen2
Linaro/meta-qcom pull request #551
Opened 2023-11-21 08:53 UTC by kraparthy

Add firmware package support for RB3Gen2

Currently, firmware zip is not posted on SRC_URI mentioned in the patch
this request to get the review done on changes

2023-11-21 08:54 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +SRC_URI ="https://artifacts.codelinaro.org/ui/native/clo-386-k2c-yocto/${FW_D_NAME}.zip"
Whitespace after '='

2023-11-21 08:56 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +SRC_URI ="https://artifacts.codelinaro.org/ui/native/clo-386-k2c-yocto/${FW_D_NAME}.zip"
Also this link doesn't seem to work. I can not test this.

2023-11-21 09:01 UTC, lumag requested changes
Also please drop the Change-ID trailers. There is no Gerrit here.

2023-11-21 09:01 UTC, lumag commented on recipes-bsp/packagegroups/packagegroup-firmware-rb3g2.bb
> +SUMMARY = "Firmware packages for the RB3Gen2 platform"
For the commit subject: please replace the glob with the package name.

2023-11-21 09:01 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +DESCRIPTION = "QCOM Firmware for Qualcomm Robotics RB3Gen2 platform"
For the package name, what exactly is `-msl`? It should be just `...-rb3g2`.

2023-11-21 09:01 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +SRC_URI ="https://artifacts.codelinaro.org/ui/native/clo-386-k2c-yocto/${FW_D_NAME}.zip"
Hi,
As i mentioned in pull request description, Currently, firmware zip is not posted on SRC_URI mentioned in the patch
this request to get the review comments on the patches
once the firmware is hosted on the link, we can close the loop
-Kiran

2023-11-21 09:02 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +SRC_URI ="https://artifacts.codelinaro.org/ui/native/clo-386-k2c-yocto/${FW_D_NAME}.zip"
Converted to the draft. Please ping me once the firmware package is available. I can not continue my review until that moment.

2023-11-21 09:14 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +LIC_FILES_CHKSUM = "file://Qualcomm-Technologies-Inc.-Proprietary;md5=58d50a3d36f27f1a1e6089308a49b403"
Could you please post this license file somewhere? I see that md5sum differs from any of the files that we saw beforehand.

2023-11-21 09:21 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +DESCRIPTION = "QCOM Firmware for Qualcomm Robotics RB3Gen2 platform"
we will have seperate zip for dsp libs, so keeping the firmware recipe name same as zip for differentiation
QCM6490_MSL.zip contains the split binaries,jsn files for ADSP(Audio)/CDSP(compute)

2023-11-21 09:22 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +DESCRIPTION = "QCOM Firmware for Qualcomm Robotics RB3Gen2 platform"
You can have a single recipe for both zip files. Please drop the -msl part.

2023-11-21 09:28 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +DESCRIPTION = "QCOM Firmware for Qualcomm Robotics RB3Gen2 platform"
Any reference pls

2023-11-21 09:35 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +DESCRIPTION = "QCOM Firmware for Qualcomm Robotics RB3Gen2 platform"
https://docs.yoctoproject.org/bitbake/2.6/bitbake-user-manual/bitbake-user-manual-fetching.html#the-download-fetch 

> If multiple URIs exist, you can specify the checksums either directly as in the previous example, or you can name the URLs. The following syntax shows how you name the URIs:

```
SRC_URI = "http://example.com/foobar.tar.bz2;name=foo"
SRC_URI[foo.md5sum] = "4a8e0f237e961fd7785d19d07fdb994d"
```

2023-11-21 09:37 UTC, lumag commented
Also could you please update `MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS` to include the new packagegroup.

2023-11-21 19:57 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +}
Do you want me to replace by defining SPLIT_FIRMARE_PACKAGES?

2023-11-21 20:14 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3g2-msl.bb
> +}
I want you to define `SPLIT_FIRMWARE_PACKAGES` so that there are severa smaller packages instead of a single monster package (like we did for other boards).

2023-11-24 13:06 UTC, lumag reviewed
- Please provide license file for the review (you can do that privately)
- Please use your real name for the S-o-b tags.

2023-11-24 13:06 UTC, lumag commented on recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
> +    firmware-qcom-rb3gen2 \
Please also list individual firmware packages:
```
    ${@bb.utils.contains('DISTRO_FEATURES', 'opengl', 'linux-firmware-qcom-adreno-a660 linux-firmware-qcom-qcm6490-adreno', '', d)} \
    ${@bb.utils.contains('DISTRO_FEATURES', 'wifi', 'linux-firmware-ath11k', '', d)} \
    ${@bb.utils.contains('DISTRO_FEATURES', 'bluetooth', 'linux-firmware-qca', '', d)} \
    linux-firmware-qcom-qcm6490-audio \
    linux-firmware-qcom-qcm6490-compute \
    linux-firmware-qcom-vpu-2.0 \
```

2023-11-24 13:33 UTC, kraparthy commented on recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
> +    firmware-qcom-rb3gen2 \
without adding the firmware package here, i observed that the packages are getting generated and felt that it is redundant . Could you pls let me know the significance of adding the firmware package name here.

2023-11-24 13:36 UTC, lumag commented on recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
> +    firmware-qcom-rb3gen2 \
First, this is to list firmware packages that come from linux-firmware rather than from your package.

Second, this is to smooth the upgrade, once your firmware migrates to linux-firmware.

The RRECOMMENDS from the base firmware package to individual packages was done to smooth upgrades to packagegroups.

2023-11-24 13:38 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
It is `a660_zap.mbn` of course.

2023-11-24 13:42 UTC, kraparthy commented on recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
> +    firmware-qcom-rb3gen2 \
got it. thanks for the details. will address this in next PS

2023-11-24 13:52 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
> Please drop the `-split` packages and use `.mbn` files instead.
Checking internally, will update accordingly

> It is `a660_zap.mbn` of course.
As of now, we dont have this as part of firmware zip. planning to add new change when this gets updated in zip
Hope, you are fine with this?

2023-11-24 13:57 UTC, kraparthy commented
> * Please use your real name for the S-o-b tags.
I am using my real name in signed of by. could you pls share the details that i can take care

2023-11-24 13:58 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
Quoting levels were broken, fixed them for you:

> > Please drop the `-split` packages and use `.mbn` files instead.

> Checking internally, will update accordingly

You can use pil-squasher tool from this repo if you need to squash them manually.


> > It is `a660_zap.mbn` of course.

> As of now, we dont have this as part of firmware zip. planning to add new change when this gets updated in zip
> Hope, you are fine with this. let us know your comments

My strong recommendation is to get all the files through the legal at one place. You might need to add Adreno Zap shader and WiFi (and maybe BT) board data files for your board. I assume that the boards work with the WiFi, BT and VPU firmware currently present in the linux-firmware. If not, please add them too.

2023-11-24 14:00 UTC, lumag commented
> > * Please use your real name for the S-o-b tags.

>    I am using my real name in signed of by. could you pls share the details that i can take care

This is from the last patch:

```Signed-off-by: kraparthy <quic_kraparth@quicinc.com>```

2023-11-28 23:53 UTC, lumag commented
@kraparthy last commit still lists `kraparthy <quic_kraparth@quicinc.com>` as commit author.

2023-12-01 10:28 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
Adreno bring up is in progress. we are planning to use linux-firmare package once bring up is done
Regarding other subsystems like BT/Wifi,VPU etc, we are working internally if we are planning to go with linux firmware package
We are planning to add the respective firmware package once the BU happens and internal team agrees to use Linux firmware package

2023-12-01 10:41 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
Adreno bringup can not be 'in progress'. Adreno 635 is fully supported by freedreno driver. So I stongly recommend to get Adreno ZAP as a part of this release. Doing otherwise would damage user experience.

Do you mean shipping the firmware via the standard `linux-firmware` repo? This is the best option, but it will take time until the firmware hits the linux-firmware and it is releases. Thus the workflow is usually the following:
- release the ZIP file
- add files to the firmware-qcom-foo package, fix the names, verify that the kernel works as expected
- send pull request to the linux-firmware 
- once the next version of linux-firmware is released, update linux-firmware in OE-core
- drop migrated files from firmware-qcom-foo

 This is the workflow that we have established after series of trial and error and so I can recommend sticking to it. The end goal should be to have firmware-qcom-foo packages nearly empty (e.g. consisting only of the dspso files). Shipping the firmware via any means other than linux-firmware doesn't work in the long term. Please don't even consider them.

For the BT, WiFi and VPU firmware I expect that current versions work for qcm6490, because they work for sc7280. If we get updates, that is good. If we do not, so be it. In other words, I would object to getting this firmware into meta-qcom for any reason other than testing it before sending to linux-firmware.

2023-12-05 12:20 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
**Adreno**: you have to add the signed ZAP shader, `a635_zap.mbn`. So it should be added to the firmware zip file.

**WLAN**: you should discuss this with ath11k maintainers. I see that there is existing WCN6750 firmware, we should stick to that or work with Kalle to get it updated. Additional note: you can not just put the board.bin file in place. You have to either get the files into linux-firmware, or repack the board-2.bin, see how it was done previously. If you have your board files ready, it's high time to submit them now to the ath11k mailing list. Otherwise it might take several months to get them in.

**BT**: same approach. Stick to the firmware in linux-firmware, get it updated if necessary.

I could not understand your question regarding the split firmware. We definitely do not want to have mdt+bNN files on the rootfs (except WiFi, which is a separate story). And I'd definitely object to putting firmware into the `firmware-qcom-something.ipk` _package_.

2023-12-06 12:30 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
Even if you are going to use proprietary driver, the zap shader should go to the firmware zip file and then to linux-firmware.

2023-12-06 13:04 UTC, lumag commented
@kraparthy Could you please clarify, does this text allow the firmware to be included into e.g. Debian cd image?
If not, this license is not acceptable from my point of view.

> (ii)  the Redistributable Binary Code may only 
operate in conjunction with platforms that contain a semiconductor product sold under QTI’s (or QTI’s affiliates’) label or manufactured under 
license from QTI (or QTI’s affiliates) (“Platform”)

2023-12-06 13:08 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
Excuse me, your statement doesn't make sense to me. The `sc7280.dtsi` includes the SMMU unit. And this is unit is not disabled.

```
                adreno_smmu: iommu@3da0000 {
                        compatible = "qcom,sc7280-smmu-500", "qcom,adreno-smmu",
                                     "qcom,smmu-500", "arm,mmu-500";
```

Let me probably put it plain and straight: NAK until there is a working zap shader binary.

2023-12-06 13:17 UTC, lumag commented
I'm reading through the license. Could you please clarify the implications by the change in the redistribution restrictions:

Current text:

> (ii)  the Redistributable Binary Code may only operate in
  conjunction with platforms incorporating Qualcomm Technologies, Inc. chipsets;

New text:

> (ii)  the Redistributable Binary Code may only 
operate in conjunction with platforms that contain a semiconductor product sold under QTI’s (or QTI’s affiliates’) label or manufactured under 
license from QTI (or QTI’s affiliates) (“Platform”);

2023-12-06 13:21 UTC, lumag commented
Also this paragraph looks troublesome:

> In addition, You shall not attempt, knowingly permit or encourage others to attempt to: (i) make any copies of the Licensed Materials except as 
otherwise permitted under Section 1.1 (License Grant) of this Agreement in the case of Software and under Section 1.3 (Documentation) of this 
Agreement in the case of Documentation; (ii) rent, lease, loan, reproduce (except as to the Redistributable Binary Code, as expressly set forth 
in Section 1.1 (License Grant) of this Agreement, and the Documentation as expressly set forth in Section 1.3 (Documentation) of this Agreement 
), modify, distribute (except as to the Redistributable Binary Code, as expressly set forth in Section 1.1 (License Grant) of this Agreement), 
publicly perform, publicly display or create derivative works of or based on the Licensed Materials, or disclose, provide or otherwise distribute 
or transfer, in any manner, to any third party the Licensed Materials or any portion thereof (except as to the Redistributable Binary Code, as 
expressly set forth in Section 1.1 (License Grant) of this Agreement); or (iii) use the Licensed Materials for any purpose other than as 
expressly permitted in the case of the Software, Section 1.1 (License Grant) of this Agreement, and in the case of Documentation, Section 1.3 
(Documentation) of this Agreement.

2023-12-06 13:27 UTC, lumag commented
Generally this license text seems troublesome. I'd like to counsel our lawyers and/or linux-firmware@ and Debian legal before accepting this pull request. I can not be 100% sure about the risks that we will partake if we create and put online the rootfs image created using these binaries. Nor can I be sure that linux-firmware maintainers and further upstream Linux distribution maintainers will accept binaries distributed under this license.

2023-12-06 16:13 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.7.bb
> +    linux-firmware-qcom-${FW_QCOM_NAME}-audio-split \
I mean based on earlier internal discussions, if access control is not enabled, there is no need of zap shadder which is the reason why for chrome , zap shadder is not pushed to linux firmware
Anyways, we are working internally on what is the plan for Gfx

2023-12-06 16:16 UTC, kraparthy commented
> Generally this license text seems troublesome. I'd like to counsel our lawyers and/or linux-firmware@ and Debian legal before accepting this pull request. I can not be 100% sure about the risks that we will partake if we create and put online the rootfs image created using these binaries. Nor can I be sure that linux-firmware maintainers and further upstream Linux distribution maintainers will accept binaries distributed under this license.

I have shared your feedback on License. we will discuss internally and update

2023-12-06 22:05 UTC, lumag commented
Thank you!

2024-02-23 14:41 UTC, lumag requested changes
@kraparthy:
- CI fails, see https://tuxapi.tuxsuite.com/v1/groups/linaro/projects/nicolas/plans/2clThhAxJjC373MBFhzvlSa7cbH
- I still don't see the Adreno shader. Please add it.

- Please provide WiFi BDF file. It can be provided later as a separate pull requst or as a part of this pull request.

2024-02-23 16:21 UTC, lumag requested changes

2024-02-23 16:21 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.12.1.bb
> +    install -m 0644 ${WORKDIR}/${FW_D_NAME}/${QCOM_FW_PATH}/*dsp*.jsn ${D}${QCOM_FW_PATH}
NAK. Installation target was correct. Also, I'd say that defining a variable with the name being a close mimic of the existing one is a bad practice. Can you really notice the difference between `QCOM_FW_PATH` and `FW_QCOM_PATH` if you just see once of them at the recipe?

2024-02-23 16:33 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.12.1.bb
> +    install -m 0644 ${WORKDIR}/${FW_D_NAME}/${QCOM_FW_PATH}/*dsp*.jsn ${D}${QCOM_FW_PATH}
As per CI failure log for the earlier patch, seems, FW_QCOM_PATH is "/usr/lib/firmware/qcom/qcm6490"  - this path doesn't exit in in the zip(during local verification, i am getting this as "/lib/firmware/qcom/qcm6490")
If the concern is only variable name, sure, i can update

Pls let me know if you have any other comments

2024-02-23 16:35 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.12.1.bb
> +    install -m 0644 ${WORKDIR}/${FW_D_NAME}/${QCOM_FW_PATH}/*dsp*.jsn ${D}${QCOM_FW_PATH}
The installation source was indeed incorrect. The installation destination dir is correct. Other comments are listed in a previous comment.

2024-02-23 16:35 UTC, kraparthy commented
> * I still don't see the Adreno shader. Please add it.
> * Please provide WiFi BDF file. It can be provided later as a separate pull requst or as a part of this pull request.

Internal team is working on pushing ZAP shader  to linux firmware git. I'll raise new request once it is pushed 
Same with WiFi BDF file

2024-02-23 16:39 UTC, lumag commented
> > * I still don't see the Adreno shader. Please add it.
> > * Please provide WiFi BDF file. It can be provided later as a separate pull requst or as a part of this pull request.
> 
> Internal team is working on pushing ZAP shader to linux firmware git. I'll raise new request once it is pushed Same with WiFi BDF file

I hope that your team is also working on pushing adsp and cdsp firmware to that repo. However once those files are a part of the `linux-firmware`,  this recipe can be mostly dropped (or simply install an next-to-empty package like other firmware recipes do). The purpose of this recipe is to provide those files before they are able to hit linux-firmware release. So, please provide it as a part of this PR. Dixi.

2024-02-23 16:48 UTC, lumag commented
it = Adreno ZAP shader.

2024-02-24 01:47 UTC, kraparthy commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_r1.0.00001.12.1.bb
> +    install -m 0644 ${WORKDIR}/${FW_D_NAME}/${QCOM_FW_PATH}/*dsp*.jsn ${D}${QCOM_FW_PATH}
Looks like, CI checks are successful now

2024-04-16 15:45 UTC, lumag commented
@kraparthy Any updates regarding the ZAP shader?

2024-04-16 15:55 UTC, kraparthy commented
> @kraparthy Any updates regarding the ZAP shader?

@lumag , Team is waiting for Legal approval to push the ZAP shader to no login firmware zip 
but it is going to happen soon
If you are okay, i can push another patch ZAP shader once Legal approval is in place. Otherwise, i can push the new patch once the Legal approval is in place and team pushes the new firmware zip

2024-04-16 15:58 UTC, lumag commented
@kraparthy I still consider firmware package to be incomplete w/o ZAP shader. Also I noticed that recent patches enable modem and wnss remoteprocs and as such they depend on modem and wnss firmware being provided, but I don't see these packages being enabled in this recipe.

2024-04-18 07:37 UTC, lumag commented
@kraparthy as this keeps

2024-04-23 05:19 UTC, adhudase commented
Hi @lumag, zap shader, modem and other firmware bins are still not available in public domain (no-login release) pending legal approval. We'll keep you posted on any updates regarding this matter.

Since @kraparthy has moved to another project and won't be able to continue with this PR, I will take over this. Shall we continue with same PR or create a new one?

Thanks

2024-04-24 01:59 UTC, lumag commented
@adhudase Please don't use 'public domain' for licensed software. It is a separate legal status with its own set of rights. We have never asked to release firmware as 'public domain'.

Regarding your question. Since you can not write to @kraparthy's tree, you will have to create new PR once requested firmware blobs become available.

2024-04-25 06:53 UTC, adhudase commented
> @adhudase Please don't use 'public domain' for licensed software. It is a separate legal status with its own set of rights. We have never asked to release firmware as 'public domain'.
> 
Sorry, my bad.

> Regarding your question. Since you can not write to @kraparthy's tree, you will have to create new PR once requested firmware blobs become available.
Sure, will do.

2024-07-30 11:51 UTC, konradybcio commented
I see that this provides `/lib/firmware/qcom/qc*m*6490`, whereas the upstream dt expects `/lib/firmware/qcom/qc*s*6490`.. which one do we go with in the end?

2024-07-30 12:14 UTC, lumag commented
I hope the upstream one. Maybe somebody confused RB3g2 (qcs) and **qcm**6490-IDP

2024-08-21 14:31 UTC, lumag commented
Replaced by #619

2024-08-21 14:31 UTC, closed without merging