Fix dependency loop between INITRAMFS_IMAGE and UKI
Linaro/meta-qcom pull request #562
Opened 2023-12-29 09:36 UTC by quic-vkraleti

Ramdisk image by default pulls in a dependency on do_packagedata task of kernel.
Uki.bbclass is trying to create kernel-uki package, by packaging ramdisk image before packagedata task. 
This is the causing circular dependency of tasks. To address this, need to stop creating kernel-uki package and place efi image in deploydir instead.

2023-12-29 22:21 UTC, lumag commented
We are back to picking up the image from deploy dir. I think it might be better to package the UKI separately from its own recipe. This way it will not be limited to just kernel+initramfs, but will simplify extending it with the splash screen, microcode, etc.

2024-01-09 10:25 UTC, lumag requested changes
Also just to point it out, starting from commit 4 you have switched to the `qti.qualcomm.com`. Please fix your git configuration and update the patches.

2024-01-09 10:25 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +}
Just rename do_uki to do_compile

2024-01-09 10:25 UTC, lumag commented on classes/uki.bbclass
> +fakeroot python do_uki() {
Why do you need fakeroot here?

2024-01-09 10:25 UTC, lumag commented on classes/uki.bbclass
> +    ${INITRAMFS_IMAGE}:do_image_complete \
This will break if `INITRAMFS_IMAGE` is not defined.

2024-01-09 10:25 UTC, lumag commented on classes/uki.bbclass
> +            elif os.path.exists(baseinitrd + imgnamesuffix + img):
If you put imgnamesuffix into play, you can skip the `baseinitrd + img` check.

2024-01-09 10:25 UTC, lumag commented on classes/uki.bbclass
> +            bb.fatal("initrd= %s must be specified to create unified kernel image." % baseinitrd)
The error message is invalid anyway. Could you please fix it instead? And the next one too.

2024-01-09 10:25 UTC, lumag commented on classes/uki.bbclass
> +    ukify_cmd += " --linux=%s --uname %s" % (d.getVar('B') + "/" + "Image", kernel_version)
This will break if `KERNEL_IMAGETYPE` is not one of `Image` / `Image.gz`.

2024-01-09 10:25 UTC, lumag commented on classes/uki.bbclass
> +        subprocess.check_call(cmd, shell=True)
It looks like this should be handled in a different way. E.g. by making sure that the user has `Image` in the `KERNEL_IMAGETYPES` instead.

2024-01-09 10:25 UTC, lumag commented on classes/uki.bbclass
> +    stub = os.path.join(d.getVar('DEPLOY_DIR_IMAGE'), "linux%s.efi.stub" % target_arch)
why?

2024-01-09 10:25 UTC, lumag commented on classes/uki.bbclass
> +    if (os.path.exists(output_dir)):
Please use existing bitbake mechanism for this

2024-01-09 10:25 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +do_configure[noexec] = "1"
Why? Default do_configure should just fall through.

2024-01-09 10:25 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +COMPATIBLE_HOST = '(x86_64.*|arm.*|aarch64.*)-(linux.*)'
If the package is called `linux-qcom-uki`, it doesn't make sense to list `x86_64` as compatible. I think it makes sense to rename the recipe to a generic one and inherently send it to OE-core for inclusion.

2024-01-09 10:25 UTC, lumag commented on conf/machine/include/qcom-common.inc
> +PREFERRED_RPROVIDER_virtual-systemd-bootconf = "qcom-systemd-bootconf"
Commit messages is not finished. Also this doesn't seem relevant to the INITRAMFS_IMAGE issue.

2024-01-09 10:25 UTC, lumag commented on recipes-core/systemd/qcom-systemd-bootconf.bb
> +}
Why do you need it at all?

2024-01-09 10:25 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +IMAGE_ROOTFS_EXTRA_SPACE = "512"
Again, irrelevant to INITRAMFS_IMAGE issue.

2024-01-10 09:12 UTC, quic-vkraleti commented on recipes-core/systemd/systemd-boot-native_254.4.bb
> -}
Ok, I'll submit it separately.

2024-01-10 09:12 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +}
Done.

2024-01-10 09:22 UTC, quic-vkraleti commented on classes/uki.bbclass
> +    ${INITRAMFS_IMAGE}:do_image_complete \
fixed.

2024-01-10 09:23 UTC, quic-vkraleti commented on classes/uki.bbclass
> +            elif os.path.exists(baseinitrd + imgnamesuffix + img):
Done.

2024-01-10 10:24 UTC, quic-vkraleti commented on classes/uki.bbclass
> +    ukify_cmd += " --linux=%s --uname %s" % (d.getVar('B') + "/" + "Image", kernel_version)
For now baling out if kernel image type is not Image/Image.gz. Will explore if there is a possibility to convert zImage, uImage, bzImage etc into Image.

2024-01-10 10:25 UTC, quic-vkraleti commented on classes/uki.bbclass
> +        subprocess.check_call(cmd, shell=True)
Sure, will explore.

2024-01-10 10:25 UTC, quic-vkraleti commented on classes/uki.bbclass
> +    stub = os.path.join(d.getVar('DEPLOY_DIR_IMAGE'), "linux%s.efi.stub" % target_arch)
to get rid of deploy_dir_image local variable.

2024-01-10 10:27 UTC, lumag commented on classes/uki.bbclass
> +    stub = os.path.join(d.getVar('DEPLOY_DIR_IMAGE'), "linux%s.efi.stub" % target_arch)
1) Unrelated changes make it harder to read the patch.
2) There is nothing wrong with local variables.

2024-01-10 10:27 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +COMPATIBLE_HOST = '(x86_64.*|arm.*|aarch64.*)-(linux.*)'
Sure will do. For now dropped x86_64 from compatible host list.

2024-01-10 10:28 UTC, lumag commented on classes/uki.bbclass
> +    ukify_cmd += " --linux=%s --uname %s" % (d.getVar('B') + "/" + "Image", kernel_version)
This is not what I have asked for.

2024-01-10 12:18 UTC, quic-vkraleti commented on recipes-kernel/images/esp-qcom-image.bb
> +IMAGE_ROOTFS_EXTRA_SPACE = "512"
will move to another pull request.

2024-01-10 12:20 UTC, lumag commented on recipes-core/systemd/qcom-systemd-bootconf.bb
> +}
This doesn't answer the question. The "is not serving needs" is not a sensible response. I can not make any judgement using it.

2024-01-10 12:28 UTC, quic-vkraleti commented on recipes-core/systemd/qcom-systemd-bootconf.bb
> +}
Will provide more details on what problems we faced in next pull request we are going to submit for this.

2024-01-10 19:11 UTC, quic-vkraleti commented on classes/uki.bbclass
> +    ukify_cmd += " --linux=%s --uname %s" % (d.getVar('B') + "/" + "Image", kernel_version)
Added Image to KERNEL_IMAGETYPES

2024-01-10 19:16 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +do_configure[noexec] = "1"
Done

2024-01-10 23:09 UTC, lumag commented on classes/uki.bbclass
> +do_configure[depends] += "${@ '${INITRAMFS_IMAGE}:do_image_complete' if d.getVar('INITRAMFS_IMAGE') else ''}"
this is just `DEPENDS = "os-release systemd-boot virtual/kernel"`

2024-01-10 23:20 UTC, lumag requested changes
We should skip building the linux-qcom-uki if `KERNEL_IMAGETYPES` doesn't contain `Image`. That's what I had in mind in my comment. Please use `SKIP_RECIPE` or `bb.parse.SkipRecipe`

2024-01-10 23:20 UTC, lumag commented on classes/uki.bbclass
>      subprocess.check_call(ukify_cmd, env=env, shell=True)
This funcion now looks completely like a shell script rewritten into python. Can we please rewrite it back to shell?

2024-01-10 23:20 UTC, lumag commented on conf/machine/include/qcom-common.inc
> +KERNEL_IMAGETYPES:append = " Image"
This is irrelevant to the linux-qcom-uki recipe. Move this to a separate commit.

2024-01-10 23:20 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +inherit uki
I think it is easier to drop uki.bbclass now, as we have it mostly rewritten. Just merge its contents here.

2024-01-11 02:24 UTC, quic-vkraleti commented on classes/uki.bbclass
>      subprocess.check_call(ukify_cmd, env=env, shell=True)
I can but what's wrong if it is written in Python?

2024-01-11 02:34 UTC, quic-vkraleti commented on classes/uki.bbclass
> +do_configure[depends] += "${@ '${INITRAMFS_IMAGE}:do_image_complete' if d.getVar('INITRAMFS_IMAGE') else ''}"
Not really. DEPENDS make current recipe's do_configure wait for do_recipe_sysroot of dependent recipes to complete. But here do_configure need to wait for do_deploy as systemd-boot & kernel recipes are not providing stub & Image as a package. So explicit task depends is still needed.

2024-01-11 09:47 UTC, lumag commented on classes/uki.bbclass
>      subprocess.check_call(ukify_cmd, env=env, shell=True)
What is wrong with having Python wrapper around shell? Probably the same as having the ineffective code in any other software piece.

2024-01-11 09:48 UTC, lumag commented on classes/uki.bbclass
> +do_configure[depends] += "${@ '${INITRAMFS_IMAGE}:do_image_complete' if d.getVar('INITRAMFS_IMAGE') else ''}"
Ack.

2024-01-16 23:37 UTC, lumag requested changes

2024-01-16 23:37 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    output="${D}${EFI_UKI_PATH}/${EFI_LINUX_IMG}"
Compile should buid the image, not install it.
${D} should only be touched in do_install.

2024-01-16 23:37 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
This is called `KERNEL_DEVICETREE`, isn't it?

2024-01-16 23:37 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +                initrd="${DEPLOY_DIR_IMAGE}/${INITRAMFS_IMAGE}-${MACHINE}${IMAGE_NAME_SUFFIX}.$img"
No need for `-${MACHINE}` here.

2024-01-16 23:37 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +        [ -f $initrd ] && echo "Creating unified kernel image with $initrd" || die "$initrd is not a valid initrd to create UKI."
`bbfatal`, please.

2024-01-17 04:38 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
KERNEL_DEVICETREE can have multiple DTB files. But within UKI we want to handle only a subset of those.  More over want to keep this section optional as per our previous discussions and move all dtb files into ESP directly. Hence decided to use a separate variable here.

2024-01-17 04:45 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
Current code doesn't have `UKI_DTB`, so it should not be a part of this PR. Please submit it separately.

2024-01-17 05:46 UTC, quic-vkraleti commented on conf/machine/include/qcom-common.inc
> +# UKI generation need uncompressed Kernel image
ack.

2024-01-17 12:32 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +                initrd="${DEPLOY_DIR_IMAGE}/${INITRAMFS_IMAGE}-${MACHINE}${IMAGE_NAME_SUFFIX}.$img"
Ah, I remember what is the issue. It should be `[ -n "${INITRAMFS_IMAGE}"]`, but after that it should be `${INITRAMFS_IMAGE_NAME}` all over the place.

2024-01-18 09:43 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +                initrd="${DEPLOY_DIR_IMAGE}/${INITRAMFS_IMAGE}-${MACHINE}${IMAGE_NAME_SUFFIX}.$img"
`INITRAMFS_IMAGE_NAME` is also defined in `image-artifact-names.bbclass`:
```
layers/openembedded-core/meta/classes-recipe/image-artifact-names.bbclass:INITRAMFS_IMAGE_NAME ?= "${@['${INITRAMFS_IMAGE}${IMAGE_MACHINE_SUFFIX}', ''][d.getVar('INITRAMFS_IMAGE') == '']}"
```

2024-01-18 11:16 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +                initrd="${DEPLOY_DIR_IMAGE}/${INITRAMFS_IMAGE}-${MACHINE}${IMAGE_NAME_SUFFIX}.$img"
Aah. I am checking on Kirkstone. This got added in Master. I am clear now and updated the change. In similar lines should we set ${IMAGE_NAME_SUFFIX} to empty for initramfs-test-full-image? Expectation is all initramfs images should set to empty.

2024-01-18 13:28 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +                initrd="${DEPLOY_DIR_IMAGE}/${INITRAMFS_IMAGE}-${MACHINE}${IMAGE_NAME_SUFFIX}.$img"
Yes, please.

2024-01-18 23:27 UTC, lumag approved these changes

2024-01-18 23:27 UTC, merged