linux-yocto: qcom-armv8a: enable NT36672E panel and PWM on QCM6490
Linaro/meta-qcom pull request #586
Opened 2024-04-03 05:37 UTC by TanguduSrihitha

Enable Novatek NT36672E panel and PWM for backlight on QCM6940.

2024-04-03 08:27 UTC, lumag requested changes

2024-04-03 08:27 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-qcm6490.cfg
> +CONFIG_BACKLIGHT_PWM=m
These are not required for the qcm6490 itself. Please move to `qcom-extra.cfg`

2024-04-08 05:48 UTC, TanguduSrihitha commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-qcm6490.cfg
> +CONFIG_BACKLIGHT_PWM=m
Ack

2024-04-08 07:37 UTC, lumag approved these changes

2024-04-15 14:44 UTC, merged

2024-04-30 22:26 UTC, lumag commented
@TanguduSrihitha @adhudase 

[INFO]: the following symbols were not found in the active configuration:
     - CONFIG_DRM_PANEL_NOVATEK_NT36672E

Please submit patches adding the panel driver