linux-yocto: refine qcm6490 kernel patches
Linaro/meta-qcom pull request #587
Opened 2024-04-04 07:33 UTC by adhudase

refine and update the qcm6490 kernel patches.

Device-tree patches: dropped old patches and backported new patches from upstream.
Clock-controllers: dropped old patches and pulled new series from mailing-list.
Updated other device-tree patches to align with new upstream dt structure.
Dropped few workarounds which are no longer needed.

2024-04-04 08:55 UTC, lumag commented
Please squash 'drop' and 'pull in' commit pairs. It is easier to review changes in this way.

2024-04-04 09:04 UTC, lumag requested changes

2024-04-04 09:04 UTC, lumag commented on recipes-kernel/linux/linux-yocto/workarounds/0001-PENDING-arm64-dts-qcm6490-Remove-voltage-voting-for-.patch
Please replace these patches with a proper limits being set for these regulators.

2024-04-04 09:04 UTC, lumag commented on recipes-kernel/linux/linux-yocto/workarounds/0001-PENDING-arm64-dts-qcm6490-Remove-voltage-voting-for-.patch
> + };
How comes the wifi/memory-region is a part of the patch touching USB-related regulators?

2024-04-04 09:04 UTC, lumag commented on recipes-kernel/linux/linux-yocto/workarounds/0002-PENDING-arm64-dts-qcs6490-rb3-Remove-voltage-voting-.patch
> ++
l10c comes after l1b/l7b/l9b.

2024-04-04 09:04 UTC, lumag commented on conf/machine/qcom-armv8a.conf
> +    qcom/qcs6490-rb3gen2.dtb \
This should be done in the same commit. Otherwise git-bisect is broken.
Rule of thumb: never ever break the build between commits.

2024-04-05 03:29 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/workarounds/0002-PENDING-arm64-dts-qcs6490-rb3-Remove-voltage-voting-.patch
> ++
Ack

2024-04-05 03:29 UTC, adhudase commented on conf/machine/qcom-armv8a.conf
> +    qcom/qcs6490-rb3gen2.dtb \
Ack

2024-04-05 03:38 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/workarounds/0001-PENDING-arm64-dts-qcm6490-Remove-voltage-voting-for-.patch
> + };
That's not an addition. ++ lines are additions. Not sure why it is highlighted. I'll check.

2024-04-05 03:44 UTC, lumag commented on recipes-kernel/linux/linux-yocto/workarounds/0001-PENDING-arm64-dts-qcm6490-Remove-voltage-voting-for-.patch
> + };
I see, it's probably context update.

2024-04-05 03:59 UTC, adhudase commented
> Please squash 'drop' and 'pull in' commit pairs. It is easier to review changes in this way.
Ack

2024-04-05 04:00 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/workarounds/0001-PENDING-arm64-dts-qcm6490-Remove-voltage-voting-for-.patch
I'll check on this with respective Engineer and update accordingly.

2024-04-16 05:09 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/workarounds/0001-PENDING-arm64-dts-qcm6490-Remove-voltage-voting-for-.patch
Patches are being prepared and the ETA is 04/30. I'll update this PR once those patches are posted.

2024-04-16 12:22 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/workarounds/0002-PENDING-arm64-dts-qcs6490-rb3-Remove-voltage-voting-.patch
> ++
Done

2024-04-16 15:44 UTC, lumag requested changes

2024-04-16 15:44 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-PENDING-arm64-dts-qcom-qcm6490-Add-UFS-nodes-for-IDP.patch
> ++	vcc-supply = <&vreg_l7b_2p952>;
So, without this change building is broken?  I can only repeat my previous comment: don't break the build. After each commit the tree should build successfully and have no known regressions.

2024-04-16 15:44 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-drivers/0005-BACKPORT-FROMLIST-clk-qcom-gcc-sc7280-Update-force-m.patch
> +Subject: [PATCH 5/6] BACKPORT: FROMLIST: clk: qcom: gcc-sc7280: Update force
Why is this patch marked as BACKPORT and FROMLIST? It is either-or.

2024-04-16 15:44 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0004-UPSTREAM-arm64-dts-qcom-Add-base-qcs6490-rb3gen2-boa.patch
> + https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git for-next)
Drop the `cherry-picked` tag please.

2024-04-16 15:44 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-UPSTREAM-dt-bindings-arm-qcom-Add-QCM6490-Fairphone-.patch
> +(cherry picked from commit 4b1a16d776b474345b12f834de1fd42bca226d90)
Drop the `cherry-picked` comment please.

2024-04-16 15:44 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-UPSTREAM-dt-bindings-arm-qcom-Add-QCM6490-IDP-and-QC.patch
> +(cherry picked from commit 06fd1dd1efde4a0bcc874de03558f6e0ba3817eb
drop

2024-04-16 15:49 UTC, lumag commented
Any chance of getting https://lore.kernel.org/linux-arm-msm/20240215103929.19357-1-quic_riteshk@quicinc.com/ (+dependencies) and https://lore.kernel.org/linux-arm-msm/20240221-rb3gen2-dp-connector-v1-0-dc0964ef7d96@quicinc.com/ (+dependencies) in?

It will enable display support. I don't see any reason for keeping it not supported.

2024-04-17 12:20 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/qcm6490-drivers/0001-FROMLIST-dt-bindings-clock-qcom-Add-compatible-for-Q.patch
> +Upstream-Status: Submitted [https://lore.kernel.org/r/20240318053555.20405-2-quic_tdas@quicinc.com]
Taniya is working on this. I've dropped this series for now and I'll revisit once proper series is posted.

2024-04-17 12:21 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/qcm6490-drivers/0005-BACKPORT-FROMLIST-clk-qcom-gcc-sc7280-Update-force-m.patch
> +Subject: [PATCH 5/6] BACKPORT: FROMLIST: clk: qcom: gcc-sc7280: Update force
Fixed it now.

2024-04-17 12:21 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-UPSTREAM-dt-bindings-arm-qcom-Add-QCM6490-Fairphone-.patch
> +(cherry picked from commit 4b1a16d776b474345b12f834de1fd42bca226d90)
Ack, fixed.

2024-04-17 12:21 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-UPSTREAM-dt-bindings-arm-qcom-Add-QCM6490-IDP-and-QC.patch
> +(cherry picked from commit 06fd1dd1efde4a0bcc874de03558f6e0ba3817eb
Ack, fixed.

2024-04-17 12:27 UTC, adhudase commented
> Any chance of getting https://lore.kernel.org/linux-arm-msm/20240215103929.19357-1-quic_riteshk@quicinc.com/ (+dependencies) and https://lore.kernel.org/linux-arm-msm/20240221-rb3gen2-dp-connector-v1-0-dc0964ef7d96@quicinc.com/ (+dependencies) in?
> 
> It will enable display support. I don't see any reason for keeping it not supported.

We are working on enabling display support and will post the patches here soon. 

DP enablement is not planned at this point.

2024-04-17 18:01 UTC, lumag commented
But display is already enabled by Bjorn, including DP support!

2024-04-18 07:46 UTC, adhudase commented
I meant enabling display/DP support on meta-qcom.

We have some issues bringing up display on meta-qcom with backported patches so I will post patches once it is resolved.
I just learnt from display team that DP is not planned and they are working on upstreaming DSI to HDMI bridge driver for RB3gen2.

2024-04-18 07:52 UTC, lumag commented
@adhudase I see. Just to point out, if it is using lt9611uxc bridge, you have to flash it with the firmware from linux-firmware. The firmware that have been used by Qualcomm isn't fully compatible with the upstream driver.

2024-04-18 07:54 UTC, lumag commented
Also, as it is WIP, let's not delay this PR with display patches. Please ping me once clock patchset is updated.

2024-04-18 07:56 UTC, lumag commented
Or if you think that it's ready, we can merge this now.

2024-04-18 08:41 UTC, adhudase commented
Yes, lets merge this. I will create a separate PR for display once ready.
I am assuming clock patches will take time, so we can pull them later once available.

Thanks for the review.

2024-04-18 11:01 UTC, lumag approved these changes

2024-04-18 11:01 UTC, merged