linux-yocto: enable various remotprocs for qcm6490 boards
Linaro/meta-qcom pull request #588
Opened 2024-04-04 07:44 UTC by adhudase

Add support for the ADSP, CDSP and WPSS remoteprocs found on SC7280 and enable various applicable remoteproc nodes for qcm6490-idp and qcs6490-rb3gen2.

2024-04-04 09:06 UTC, lumag requested changes

2024-04-04 09:06 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-FROMLIST-arm64-dts-qcom-qcm6490-idp-Enable-various-r.patch
> ++	firmware-name = "qcom/qcm6490/wpss.mdt";
mbn only

2024-04-04 09:06 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-FROMLIST-arm64-dts-qcom-qcs6490-rb3gen2-Enable-vario.patch
> ++	firmware-name = "qcom/qcm6490/wpss.mdt";
mbn

2024-04-05 04:03 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-FROMLIST-arm64-dts-qcom-qcm6490-idp-Enable-various-r.patch
> ++	firmware-name = "qcom/qcm6490/wpss.mdt";
Ack. This was intentional for draft PR as I don't see mbn format for modem and wpss yet. I'll update it to mbn when ready.

2024-04-05 04:03 UTC, adhudase commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-FROMLIST-arm64-dts-qcom-qcs6490-rb3gen2-Enable-vario.patch
> ++	firmware-name = "qcom/qcm6490/wpss.mdt";
Ack. This was intentional for draft PR as I don't see mbn format for modem and wpss yet. I'll update it to mbn when ready.

2024-04-05 04:05 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-FROMLIST-arm64-dts-qcom-qcs6490-rb3gen2-Enable-vario.patch
> ++	firmware-name = "qcom/qcm6490/wpss.mdt";
Use https://github.com/linux-msm/pil-squasher

2024-04-24 02:03 UTC, lumag commented
@adhudase could you please update / rebase this PR?

2024-04-25 05:55 UTC, adhudase commented
Sure, fixing the rebase. I'll update this PR once upstream patches are updated by Komal.

2024-04-25 06:45 UTC, lumag commented
@adhudase But there is one already, it was picked up by Bjorn: https://lore.kernel.org/linux-arm-msm/171373856754.1196479.8348340567259271476.b4-ty@kernel.org/

2024-04-25 07:08 UTC, lumag commented
@adhudase I mean, there is an updated series by Komal, it has been picked up by Bjorn.

2024-04-25 10:31 UTC, adhudase commented
Hi @lumag, there was internal discussion around your comments regarding separate firmware folders for qcs6490 vs qcm6490 and modem vs modem-nm, which is not yet concluded. I will wait for that to conclude and then update this PR accordingly.

Thanks

2024-04-29 15:42 UTC, lumag commented
@adhudase the patches are already picked up for -next. So if there are any changes, you have to base it on top of the accepted patches.

2024-05-22 06:59 UTC, lumag commented
@adhudase any updates? A cadence of several weeks is really depressing

2024-06-20 13:42 UTC, lumag commented
@adhudase any updates

2024-06-27 11:04 UTC, adhudase commented
Hi @lumag, sorry for delay in response; somehow missed your message. I still don't see zap shader in no-login release and modem is not expected to be shipped in no-login. So if you agree can we go ahead with firmware recipe without these?
Thanks

2024-06-27 11:07 UTC, lumag commented
@adhudase The main question was about firmware names in DT, not about them being present in the public archive. Please update to the latest series picked up by Bjorn and that's it.

2024-06-28 07:16 UTC, adhudase commented
Seems mainline went ahead with mdt for modem on qcs6490;missed mbn. I've modified that to mbn here.
qcom/qcs6490/modem.mdt -> qcom/qcs6490/modem.mbn

2024-06-28 07:29 UTC, lumag commented
@adhudase thanks! please mark it as 'ready', I'll merge it. Also please send a patch to linux-arm-msm, changing `.mdt` to `.mbn`. Thank you!

2024-06-28 07:29 UTC, lumag approved these changes

2024-07-04 07:05 UTC, adhudase commented
Hi @lumag, can we merge this PR?

2024-07-04 07:34 UTC, lumag commented
For some reason, I didn't get the notification that it's marked as ready. Merged now.

2024-07-04 07:35 UTC, merged

2024-07-17 07:03 UTC, Thejesh99 commented
i have a qualcomm robotics RB3 gen2 vision kit 
can u please provide me a yocto guide for qualcomm robotics RB3 gen2 vision kit 
or any github repo and distro file
Regards
Thejesh