linux-yocto: enable display on QCM6490 IDP board
Linaro/meta-qcom pull request #593
Opened 2024-05-15 13:05 UTC by TanguduSrihitha

Add support for PM7250B PMIC, Novatek NT36672E DSI panel and enable display subsystem on QCM6490 IDP board.

2024-05-17 10:28 UTC, lumag requested changes
Please also pick up the DP changes from the list.

2024-05-17 10:28 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-drivers/0002-UPSTREAM-drm-panel-Add-support-for-Novatek-NT36672E-.patch
> ++	mipi_dsi_device_unregister(ctx->dsi);
There were fixups for this driver. Please pick them up too.

2024-05-17 10:28 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-extra.cfg
> +CONFIG_DRM_PANEL_NOVATEK_NT36672E=y
Please describe the issue that you have and how does this fix the issue?

2024-05-19 22:04 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-DENIED-arm64-dts-qcom-qcm6490-idp-disable-gpu.patch
> +Upstream-Status: Denied [https://lore.kernel.org/all/99a9a562-9f6f-411c-be1c-0a28fc2524dd@quicinc.com/]
Simply: NAK. The GPU is present onboard, so there is no need to disable it.

2024-05-19 22:46 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-DENIED-arm64-dts-qcom-qcm6490-idp-disable-gpu.patch
> +Upstream-Status: Denied [https://lore.kernel.org/all/99a9a562-9f6f-411c-be1c-0a28fc2524dd@quicinc.com/]
Moreover, per Ritesh's [email](https://lore.kernel.org/linux-arm-msm/7932ccbb-3b41-49e2-bb88-9c2633002a0d@quicinc.com/) this patch is not necessary at all. GPU works on this platform.

2024-05-20 11:16 UTC, TanguduSrihitha commented
> Please also pick up the DP changes from the list.

DP is currently not planned and hence not enabled.

2024-05-20 11:16 UTC, TanguduSrihitha commented on recipes-kernel/linux/linux-yocto/qcm6490-drivers/0002-UPSTREAM-drm-panel-Add-support-for-Novatek-NT36672E-.patch
> ++	mipi_dsi_device_unregister(ctx->dsi);
Sure, will pick them in the next patch.

2024-05-20 11:19 UTC, lumag commented
@TanguduSrihitha 

>> Please also pick up the DP changes from the list.

> DP is currently not planned and hence not enabled.

DP is present on the board. The patches are available for the feature. Please pick them or provide a good reason to ignore them ('not planned' is not a good reason to leave users with the disabled feature for which the support has been implemented already).

2024-05-21 08:15 UTC, lumag commented
@TanguduSrihitha Please excuse me, I got confused between IDP and RB3g2. There were no DisplayPort patches, so this is fine. Please fix the remaining issues:
- GPU node disablement
- missing panel driver fixes
- explanation for config changes

2024-05-22 06:21 UTC, TanguduSrihitha commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-extra.cfg
> +CONFIG_DRM_PANEL_NOVATEK_NT36672E=y
With the above configs set to m, when I tried initially it was working. But later on I found that on multiple reboots, it's not working most of the time. But when the above configs are set as y, the device boots to shell consistently. In the failure case, the device is getting stuck before UFS enumeration and hence the panel and backlight modules are not loaded. 

DSI PHY supply(vreg_l10c_0p88) is shared among UFS and USB as well. We tried below experiments suspecting it is a shared resource issue:

1)  As the UFS enumeration is not happening, we tried removing the PHY supply reference from the driver, the PHY probe is going ahead, but the issue is still there.
2) We removed disable vote on the PHY supply but the issue persists.

So, it's not related to the shared supply between DSI PHY and UFS.

**Below are the last set of logs in the failure case:**

[    1.824887] platform ae01000.display-controller: Fixed dependency cycle(s) with /soc@0/display-subsystem@ae00000/dsi@ae94000
[    1.837031] platform ae01000.display-controller: Fixed dependency cycle(s) with /soc@0/display-subsystem@ae00000/dsi@ae94000
[    1.848618] platform ae94000.dsi: Fixed dependency cycle(s) with /soc@0/display-subsystem@ae00000/dsi@ae94000/panel@0
[    1.859535] platform ae94000.dsi: Fixed dependency cycle(s) with /soc@0/display-subsystem@ae00000/display-controller@ae01000
[    1.874211] msm_dsi ae94000.dsi: supply refgen not found, using dummy regulator
[    1.882201] msm_dsi ae94000.dsi: Fixed dependency cycle(s) with /soc@0/display-subsystem@ae00000/dsi@ae94000/panel@0
[    1.893073] mipi-dsi ae94000.dsi.0: Fixed dependency cycle(s) with /soc@0/display-subsystem@ae00000/dsi@ae94000
[    1.904303] printk: console [netcon0] enabled
[    1.908812] netconsole: network logging started
[    1.919298] clk: Disabling unused clocks
[    2.028658] scsi 0:0:0:49488: Well-known LUN    MICRON   MT256GARAT4U313Q 0104 PQ: 0 ANSI: 6
[    2.041892] scsi 0:0:0:49476: Well-known LUN    MICRON   MT256GARAT4U313Q 0104 PQ: 0 ANSI: 6
[    2.052772] scsi 0:0:0:49456: Well-known LUN    MICRON   MT256GARAT4U313Q 0104 PQ: 0 ANSI: 6

I tried debugging but I didn't get any breakthrough, so we decided to go with y.

2024-05-22 06:35 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-extra.cfg
> +CONFIG_DRM_PANEL_NOVATEK_NT36672E=y
This doesn't answer the question, **why** it is not working. So, the issue needs to be debugged and solved properly.

2024-05-22 06:37 UTC, TanguduSrihitha commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-DENIED-arm64-dts-qcom-qcm6490-idp-disable-gpu.patch
> +Upstream-Status: Denied [https://lore.kernel.org/all/99a9a562-9f6f-411c-be1c-0a28fc2524dd@quicinc.com/]
Few of the Conrad's Adreno 643+ fixes are yet to be backported. We are in discussion with our GPU team regarding the same and adreno firmware loading enablement.

2024-05-22 06:40 UTC, lumag commented on recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-extra.cfg
> +CONFIG_DRM_PANEL_NOVATEK_NT36672E=y
Please consider discussing the topic with the UFS team and with @Mani-Sadhasivam , upstream ufs-qcom maintainer. Anyway, building the panel to the kernel is not a proper fix for the UFS issue.

2024-05-22 06:53 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-DENIED-arm64-dts-qcom-qcm6490-idp-disable-gpu.patch
> +Upstream-Status: Denied [https://lore.kernel.org/all/99a9a562-9f6f-411c-be1c-0a28fc2524dd@quicinc.com/]
GPU on SC7280 has been supported upstream since 5.16. ZAP shader has been supported for ages. I fail to see what is so special about the QCM6490 which is supposed to be very close to SC7280.

2024-05-22 06:55 UTC, lumag commented on recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-DENIED-arm64-dts-qcom-qcm6490-idp-disable-gpu.patch
> +Upstream-Status: Denied [https://lore.kernel.org/all/99a9a562-9f6f-411c-be1c-0a28fc2524dd@quicinc.com/]
So, yes, please backport the patches and provide the firmware for the board.

2024-06-20 13:26 UTC, lumag commented
@TanguduSrihitha any updates?

2024-07-01 10:12 UTC, lumag commented
@adhudase @TanguduSrihitha another ping.

2024-07-05 09:02 UTC, TanguduSrihitha commented
Hi @lumag, sorry for the delay in response.

**1) Compiling panel and PWM as modules:** We have worked with the internal stability team and got forced crash dumps when the device is stuck. Many debug configs are not enabled by default and it took multiple iterations for us to get a parsable dump. From the tasks list and stack traces of the parsed dump, we found that the device is going into a deadlock due to clk prepare_lock MUTEX. We are working with the internal clock team to identify the root cause. 

**2) Missing panel driver fixes:** I'll update in the next patch once we conclude on the panel and PWM configs setting.

**3) Backporting of Conrad's fixes and Adreno firmware loading enablement:** The GPU team is currently busy with Lemans and they'll consider support on 0.0/meta-qcom post that, probably after 7/15.

2024-08-19 12:41 UTC, lumag commented
@TanguduSrihitha any updates? We are past 15th of August.

2024-11-30 12:46 UTC, lumag commented
This becomes outdated, closing for now. Please reopen if there is an update.

2024-11-30 12:46 UTC, closed without merging