Enhance cmdline handling in linux-qcom-uki.bb
Linaro/meta-qcom pull request #618
Opened 2024-07-30 06:00 UTC by quic-vkraleti

Construct kernel cmdline by reading QCOM_BOOTIMG_ROOTFS, SERIAL_CONSOLES and KERNEL_CMDLINE_EXTRA variables and update the same into uki cmdline.

2024-07-30 23:49 UTC, lumag requested changes

2024-07-30 23:49 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
`QCOM_BOOTIMG_ROOTFS` varies per dtb. Please take that into account.

2024-07-30 23:49 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
We have similar code in `linux-qcom-bootimg.bbclass`, please consider extracting a function to OE-Core / `kernel.bbclass`.

For the reference:
```Python
        consoles = ' '.join(map(lambda c: "console=%(tty)s,%(rate)sn8" % dict(zip(("rate", "tty"), c.split(';'))), getVarDTB("SERIAL_CONSOLES").split()))
```

2024-08-05 12:02 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
KERNEL_CMDLINE_EXTRA is a meta-qcom variable. OE-Core kernel.bbclass don't support updating cmdline. For now do consider kernel cmdline setting to be a meta-qcom specific implementation only. I'll try to submit a proposal to oe-core but not sure how far it'll fly.

2024-08-05 12:02 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
@lumag if you recollect discussions in https://github.com/Linaro/meta-qcom/pull/548, we agreed to make UKI, dtb agnostic and keep a separate dtb section in ESP. We also discussed an approach to have a new partition to host dtb files.  So updating cmdline in UKI that varies per dtb won't be feasible.

2024-08-08 10:27 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
@lumag submitted PR: https://github.com/Linaro/meta-qcom/pull/620 to move DTB away from esp and create a separate dtb image. With this dtb and uki are completely isolated.

2024-08-12 09:31 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
Ack. Please cc me if you post such a patch.

2024-08-12 09:32 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
The issue is that all those variables wary from machine to machine. So you end up with an image that is expected to be generic, but in reality it isn't.

2024-08-12 10:01 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
I don't have a good solution for the issue. maybe a setup-specific DT overlay to be applied by the EFI/bootloader. Maybe a bootloader should set them.

2024-08-12 10:02 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    fi
I'm going to merge this, but let's think for a longer-term plan.

2024-08-12 10:02 UTC, merged