Add firmware package support for QCS6490 RB3Gen2
Linaro/meta-qcom pull request #619
Opened 2024-08-07 11:09 UTC by adhudase

Add firmware package support for QCS6490 RB3Gen2 board.

2024-08-07 11:52 UTC, quaresmajose commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +ADRENO_URI = "https://artifacts.codelinaro.org/artifactory/qli-ci/software/chip/qualcomm_linux-spf-1-0/qualcomm-linux-spf-1-0_test_device_public/r1.0_${PV}/le-qclinux-1-0-r1/apps_proc/prebuilt_HY22/a
please use `;fwpath=${nonarch_base_libdir}/firmware` otherwise it fail in 'usrmerge'

2024-08-07 11:52 UTC, quaresmajose commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +QCM6490_FW_SRC_PATH = "/lib/firmware/qcom/qcs6490"
please use `${nonarch_base_libdir}/firmware/qcom/qcs6490` otherwise it fail in 'usrmerge'

2024-08-07 11:52 UTC, quaresmajose commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +SRC_URI[md5sum] = "8bf745bd5ff92d891463968ed4583892"
the md5sum is not used anymore in bitbake and so i can be droped

2024-08-08 06:41 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +ADRENO_URI = "https://artifacts.codelinaro.org/artifactory/qli-ci/software/chip/qualcomm_linux-spf-1-0/qualcomm-linux-spf-1-0_test_device_public/r1.0_${PV}/le-qclinux-1-0-r1/apps_proc/prebuilt_HY22/a
Thanks for review. Ack.

2024-08-08 06:41 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +QCM6490_FW_SRC_PATH = "/lib/firmware/qcom/qcs6490"
Ack

2024-08-08 06:42 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +SRC_URI[md5sum] = "8bf745bd5ff92d891463968ed4583892"
Ack

2024-08-08 07:27 UTC, lumag requested changes

2024-08-08 07:27 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +BB_CHECK_SSL_CERTS = "0"
No need to, please drop

2024-08-08 07:27 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    if [ -n "${ADRENO_URI}" ] ; then
No need to, it is always defined.

2024-08-08 07:27 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +        install -m 0644  ${UNPACKDIR}/adreno/${ADRENO_PATH}/a660_zap.mbn ${D}${FW_QCOM_BASE_PATH}
NAK, zap goes with the rest of signed files.

2024-08-08 07:27 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +LICENSE_FILE = "Qualcomm-Technologies-Inc.-Proprietary"
Could you please add a comment with the verbatim text if the licence to the PR.

2024-08-08 07:27 UTC, lumag commented on recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
> +    firmware-qcom-rb3gen2 \
Please use separate packages for DSP firmware, as supported by firmware-qcom.inc

2024-08-08 07:27 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +DEPENDS += "pil-squasher-native"
What for?

2024-08-08 07:39 UTC, lumag commented
CI log shows that it wasn't even tested. Please don't submit untested patches.

2024-08-08 07:43 UTC, lumag commented
Also please describe in the PR description, why you are opening a new one for the same purpose as the existing one, #551.

2024-08-09 08:20 UTC, lumag commented
Also, what is the plan for the WiFi BDF files? Have you sent them to ath11k@ ML? Are you going to provide a patched board-2.bin as a part of this recipe?

2024-08-14 09:50 UTC, adhudase commented on recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
> +    firmware-qcom-rb3gen2 \
Ack

2024-08-14 09:50 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +DEPENDS += "pil-squasher-native"
Ack, will remove.

2024-08-14 09:54 UTC, adhudase commented
Thanks for review @lumag.

We have plans to share the WiFi BDF files, but I don’t have a specific date yet. Unfortunately, since board-2.bin is also not available in CLO, I cannot provide it in this recipe.

2024-08-14 10:03 UTC, lumag commented
You can rebuild it, please see the history of dragonboard/RB firmware recipes.

2024-08-19 12:38 UTC, lumag commented
@adhudase any updates?

2024-08-20 05:10 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +ADRENO_URI = "https://artifacts.codelinaro.org/artifactory/qli-ci/software/chip/qualcomm_linux-spf-1-0/qualcomm-linux-spf-1-0_test_device_public/r1.0_${PV}/le-qclinux-1-0-r1/apps_proc/prebuilt_HY22/a
Hi @quaresmajose, realized that this is a firmware source path in our zip so we cannot change it. I believe this shouldn't be a concern for usrmerge. Firmware installation to destination folder is aligned to usrmerge - using FW_QCOM_PATH.

2024-08-20 05:10 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +QCM6490_FW_SRC_PATH = "/lib/firmware/qcom/qcs6490"
same here- realized that this is a firmware source path in our zip so we cannot change it. I believe this shouldn't be a concern for usrmerge. Firmware installation to destination folder is aligned to usrmerge - using FW_QCOM_PATH.

2024-08-20 05:13 UTC, adhudase commented
Sorry, I was OOTO; looking into this now. Had some issues using ath11k-generate-board-2_json.sh/ath10k-bdencoder. I'll update it today. Thanks

2024-08-20 06:21 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +LICENSE_FILE = "Qualcomm-Technologies-Inc.-Proprietary"
@lumag shared LICENSE through email. It seems same as one at linux-firmware - https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/LICENSE.qcom.

I need to update recipe to use this license.

2024-08-20 06:31 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +QCM6490_FW_SRC_PATH = "/lib/firmware/qcom/qcs6490"
Ack

2024-08-20 06:31 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +ADRENO_URI = "https://artifacts.codelinaro.org/artifactory/qli-ci/software/chip/qualcomm_linux-spf-1-0/qualcomm-linux-spf-1-0_test_device_public/r1.0_${PV}/le-qclinux-1-0-r1/apps_proc/prebuilt_HY22/a
Ack

2024-08-20 07:54 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +LICENSE_FILE = "Qualcomm-Technologies-Inc.-Proprietary"
Thanks!

2024-08-20 08:31 UTC, quaresmajose commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +ADRENO_URI = "https://artifacts.codelinaro.org/artifactory/qli-ci/software/chip/qualcomm_linux-spf-1-0/qualcomm-linux-spf-1-0_test_device_public/r1.0_${PV}/le-qclinux-1-0-r1/apps_proc/prebuilt_HY22/a
right, the `fwpath` is to get the files inside the zip archive. the target dir is already defined on: https://github.com/Linaro/meta-qcom/blob/3e1246a93a9a013273e4e68a28df047e8cb55510/recipes-bsp/firmware/firmware-qcom.inc#L12

sorry for the noise.

2024-08-20 08:43 UTC, lumag commented
@adhudase as a side note please use Adreno SQE and GMU binaries from the main Linux-firmware repo, unless there is a **really** good reason to update those files.

2024-08-20 08:48 UTC, lumag commented
If an update is pending, feel free to provide updated files (using alternatives/preferred provider mechanism), but at least that should be documented as a temporal solution with the clear date when upstream is updated.

2024-08-20 09:05 UTC, lumag commented
>  Had some issues using ath11k-generate-board-2_json.sh/ath10k-bdencoder. I'll update it today. 

I'm fine with getting bdwlan later on, if you can not resolve the issues. Ping me next week and we can try solving them.

2024-08-20 10:13 UTC, adhudase commented
@lumag updated PR and addressed review comments. Please take a look. Thanks

2024-08-20 10:55 UTC, lumag requested changes

2024-08-20 10:55 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    https://artifacts.codelinaro.org/artifactory/qli-ci/software/chip/qualcomm_linux-spf-1-0/qualcomm-linux-spf-1-0_test_device_public/r1.0_${PV}/QCM6490.LE.1.0/common/build/ufs/bin/${FW_D_NAME}.zip;
Please use name and `SRC_URI[foo.sha256sum]`

2024-08-20 10:55 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    "
Isn't it a part of the zip file? Usually licence must be a part of the archive.

2024-08-20 10:55 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +"
Also -adreno. I'd also add -wifi and push board-2.bin there.

2024-08-20 10:55 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    install -m 0444 ${S}/board-2.bin ${D}${nonarch_base_libdir}/firmware/ath11k/QCA6750/hw1.0/board-2.bin
Which driver loads data from the QCA6750 subdir? Linux-firmware uses WCN6750

2024-08-20 11:02 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    "
No, its not part of the archive; its a separate file outside archive. moreover its .pdf.

2024-08-20 11:03 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    install -m 0444 ${S}/board-2.bin ${D}${nonarch_base_libdir}/firmware/ath11k/QCA6750/hw1.0/board-2.bin
:( sorry, typo.

2024-08-20 11:13 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +"
As a second thought, ignore -wifi. Just adreno, please

2024-08-20 11:23 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    "
Then what stops rogue person from telling that files in the archive are provided under the MIT licence? 
Moreover, you have added a text file, so I can not understand your comment regarding PDF.

2024-08-20 12:19 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    "
Its proprietary license but is placed outside archive, not sure why.

I was referring to this license pdf which is placed outside archive.
https://artifacts.codelinaro.org/ui/repos/tree/General/qli-ci/software/chip/qualcomm_linux-spf-1-0/qualcomm-linux-spf-1-0_test_device_public/r1.0_00039.2/QCM6490.LE.1.0/common/build/ufs/bin/NO.LOGIN.BINARY.LICENSE.QTI.pdf

2024-08-20 12:33 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    "
> qli-ci/software/chip/qualcomm_linux-spf-1-0/qualcomm-linux-spf-1-0_test_device_public/r1.0_00039.2/QCM6490.LE.1.0/common/build/ufs/bin/NO.LOGIN.BINARY.LICENSE.QTI.pdf could not be found.

2024-08-20 12:38 UTC, lumag commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    "
My suggestion would be to add this file to SRC_URI and install it as a part of the package. At least then we can trace that licence has been placed next to the archive. Install and handle the text version as you are currently doing. Add a comment that PDF and txt files have exactly the same text.

2024-08-21 03:55 UTC, lumag commented
@adhudase I noticed that several commits lack your SoB tag. Please add it

2024-08-21 04:38 UTC, adhudase commented on recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
> +    "
will install both and add appropriate comments.

2024-08-21 14:29 UTC, lumag approved these changes

2024-08-21 14:29 UTC, merged

2024-08-21 14:29 UTC, lumag commented
Thank you!

2024-08-26 05:19 UTC, lumag commented
@adhudase I'm really unsatisfied and surprised here. I could not manually verify the PR while merging it. In fact I had no reason not to trust that it does what it promises. However, generated WiFi board file is empty. This means that you haven't tested the code that you are submitting. First iteration of this PR also wasn't tested at all (it failed to build images because of the file conflict). Please actually verify what you are doing before submitting code upstream.

```
hexdump -C tmp-rpb-glibc/work/all-linaro-linux/firmware-qcom-rb3gen2/00039.2/image/usr/lib/firmware/ath11k/WCN6750/hw1.0/board-2.bin
00000000  51 43 41 2d 41 54 48 31  31 4b 2d 42 4f 41 52 44  |QCA-ATH11K-BOARD|
00000010  00 6d 6d 6d                                       |.mmm|
00000014
```

2024-08-26 05:59 UTC, lumag commented
@adhudase please post full dmesg of RB3gen2, including the WiFi startup messages.