Generate an image by combining all DTB files.
Linaro/meta-qcom pull request #620
Opened 2024-08-08 10:11 UTC by quic-vkraleti

This change introduces two new recipes
  * linux-qcom-combinedtb.bb - combines all .dtb files generated by kernel into a single binary blob.
  * dtb-qcom-image.bb - generates a vfat image by packaging the combined-dtb generated by linux-qcom-combinedtb recipe.

As UEFI has the ability to load vfat image and extract the dtb with matching board id, this combined-dtb helps to use a single dtb image across various boards. 

This also helps to meet one of the SystemReady IR requirements of keeping DTB out of kernel binary.

2024-08-08 14:09 UTC, ricardosalveti commented on recipes-kernel/images/dtb-qcom-image.bb
> +COMPATIBLE_HOST = '(x86_64.*|arm.*|aarch64.*)-(linux.*)'
Do we need to define compatible host? This is just creating a vfat image.

2024-08-08 14:12 UTC, ricardosalveti commented
I would also split this change in at least 2 commits, one adding the recipe and another the image.

2024-08-08 14:38 UTC, quaresmajose commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +    import os, shutil, subprocess
the `subprocess` is not used so it can be dropped

2024-08-09 08:37 UTC, lumag requested changes
- please split into two commits
- please describe, how the dtb us going to be selected. Refer existing standards, etc. Note, that using qcom,msm-id and qcom,board-id is generally frowned upon by DT maintainers and are forbidden to be used for new devices.

As a general note, I dislike the idea of a single merged dtb image just as a concatenation of all DT files. It is not easily extensible, overriding it also is not easy. If not for the SecureBoot, I'd have suggested following DtbLoader way (dtb/CHID.dtb). However with SecureBoot being an important thing the DTB provisioning mechanism should leave place for the signature verification. I would suggest exploring either a set of PE files, each having one or several DTB sections and a signature, a FIT image with a signature or just external .pk7 signature being placed next to each dtb file.

2024-08-09 08:37 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
Isn't it just `cat ${DEPLOY_DIR_IMAGE} > ${B}/combined-dtb.dtb` ? Shell script will be shorter.

2024-08-09 08:37 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +COMPATIBLE_HOST = '(arm.*|aarch64.*)-(linux.*)'
No need to.

2024-08-09 08:37 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +LICENSE = "BSD-3-Clause-Clear"
MIT, please

2024-08-09 09:02 UTC, lumag commented
Also please make sure that your new recipes are included into the CI build.

2024-08-12 08:50 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +COMPATIBLE_HOST = '(arm.*|aarch64.*)-(linux.*)'
Removed COMPATIBLE_HOST.

2024-08-12 09:08 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +    import os, shutil, subprocess
Done.

2024-08-12 09:10 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
No it is not a simple concatenation of all files under DEPLOY_DIR_IMAGE. There are symlinks of each dtb and those need to be omitted. There could be more files as well which other recipes may put under DEPLOY_DIR_IMAGE.

2024-08-12 09:11 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +LICENSE = "BSD-3-Clause-Clear"
Done.

2024-08-12 09:12 UTC, quic-vkraleti commented on recipes-kernel/images/dtb-qcom-image.bb
> +COMPATIBLE_HOST = '(x86_64.*|arm.*|aarch64.*)-(linux.*)'
Removed COMPATIBLE_HOST.

2024-08-12 09:29 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
Still a shell script with a for loop will be shorter and easier to understand.

2024-08-12 09:58 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
Ok, I'll convert this into a shell script and update.

2024-08-12 10:11 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
Other point: consider using`KERNEL_DEVICETREE` instead of looping over all dtb files

2024-08-12 10:16 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
Well I thought the same but couldn't do it because of the way dtbs are added in 
https://github.com/Linaro/meta-qcom/blob/master/conf/machine/qcom-armv8a.conf#L26

At preset DTBs are kernel recipe specific. So using KERNEL_DEVICETREE is not possible. Thus ended up looping over all generated files.

2024-08-12 11:10 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
Ack could you please leave a Todo comment with an explanation.

2024-08-12 15:03 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
Added TODO in linux-qcom-combined.bb file. Also updated DESCRIPTION in dtb-qcom-image.bb

2024-08-13 00:30 UTC, ricardosalveti commented on recipes-kernel/images/dtb-qcom-image.bb
> +                There is no DTB presence in ESP image. UKI have no .dtb section either."
This last line can be removed, as it is outside the scope of this image. An user could later have both the dtb partition (with concatenated dtbs) and UKIs with OS-provided dtbs.

2024-08-13 09:07 UTC, quic-vkraleti commented on recipes-kernel/images/dtb-qcom-image.bb
> +                There is no DTB presence in ESP image. UKI have no .dtb section either."
Removed.

2024-08-13 09:48 UTC, quic-vkraleti commented
> * please split into two commits
Done.

> * please describe, how the dtb us going to be selected. Refer existing standards, etc. Note, that using qcom,msm-id and qcom,board-id is generally frowned upon by DT maintainers and are forbidden to be used for new devices.
Updated description in dtb-qcom-image.bb describing how combined-dtb is put into use. 

> 
> As a general note, I dislike the idea of a single merged dtb image just as a concatenation of all DT files. It is not easily extensible, overriding it also is not easy. If not for the SecureBoot, I'd have suggested following DtbLoader way (dtb/CHID.dtb). However with SecureBoot being an important thing the DTB provisioning mechanism should leave place for the signature verification. I would suggest exploring either a set of PE files, each having one or several DTB sections and a signature, a FIT image with a signature or just external .pk7 signature being placed next to each dtb file.

Discussions in progress with other stake holders on alternative proposals like "keep a DTB in UKI and pass the same to Linux instead of what is provided by UEFI". Once there is a conclusion, will share a PR for the same.

> Also please make sure that your new recipes are included into the CI build.
Sure. What is the best place for adding a dependency on esp & dtb images to get built by default?

2024-08-13 09:49 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +                    shutil.copyfileobj(fin, fout)
Done.

2024-08-13 11:01 UTC, lumag commented
Yes, I saw that. However it is not acceptable. The `qcom,board-id` property isn't allowed to be used on the affected SoCs, see [arm/qcom.yaml](https://www.kernel.org/doc/Documentation/devicetree/bindings/arm/qcom.yaml)

2024-08-13 11:05 UTC, lumag commented
> keep a DTB in UKI and pass the same to Linux instead of what is provided by UEFI

This is good as an override, not I don't think it will be acceptable for System ready. Please review the old DtbLoader proposal of passing multiple dtb files via the <ESP>/dtb/<CHID>.dtb, where CHID is generated from the platform properties (like Windows and fwupdate do).

2024-08-13 11:07 UTC, lumag commented
> Sure. What is the best place for adding a dependency on esp & dtb images to get built by default?

Please extend the CI config in this repo. Be sure not to enable new images for the branches which don't have corresponding recipe.

2024-08-15 02:25 UTC, ricardosalveti commented
> This is good as an override, not I don't think it will be acceptable for System ready.

SR just requires the firmware to provide a DTB that is compliant with the spec, the issue here is that the DTB provided by the firmware is not going to be compliant, but the way it gets loaded is outside the SR scope. It is possible to have the DTB available via the firmware directory (ESP/FIRMWARE), but that is optional.

IIRC the idea is also to have the firmware providing a generic and upstream aligned device tree when the partition is not available (or empty), which can be a tradeoff until we're done with the the board-id / compatible string upstream discussion.

2024-08-15 02:29 UTC, ricardosalveti commented
> Discussions in progress with other stake holders on alternative proposals like "keep a DTB in UKI and pass the same to Linux instead of what is provided by UEFI". Once there is a conclusion, will share a PR for the same.

Supporting DTB loading via UKI is going to be needed anyway, even if the firmware is or not providing any DTB before UKI. DTB via UKI is basically allowing the OS to take control of the DTB content (which is also a valid use case).

2024-08-19 12:33 UTC, lumag requested changes

2024-08-19 12:36 UTC, lumag commented
> the DTB provided by the firmware is not going to be compliant

Could you please be more specific, which DTB is it and why isn't it compliant? Can we replace it with the proper, compliant DTB?

2024-08-19 12:37 UTC, lumag commented on recipes-kernel/images/dtb-qcom-image.bb
> +
Or rather ..  isn't a proper/sensible package description

2024-08-19 13:25 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +SRC_URI = ""
No need of? setting empty SRC_URI? marking do_fetch, do_unpack, do_patch as noexec? Or both? These are added to avoid potential setscene errors that can happen while eSDK generation.

2024-08-19 13:39 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +SRC_URI = ""
Actually both. 
What kind of errors did you observe and how to reproduce them?

2024-08-19 15:27 UTC, ricardosalveti commented
> > the DTB provided by the firmware is not going to be compliant
> 
> Could you please be more specific, which DTB is it and why isn't it compliant? Can we replace it with the proper, compliant DTB?

Selection done by the boot firmware is still done with qcom,board-id, for example. Moving away from that is a larger discussion that is going in parallel.

2024-08-19 16:23 UTC, lumag commented
@ricardosalveti can we flash a single DTB and ignore selection completely?

2024-08-19 16:33 UTC, lumag commented
I think there are two distinct questions: 
- a DTB to be used by default (e.g. for SR tests)
- a DTB to be used for booting the feature full system

From the SR perspective it should be fine if the UEFI provides a not-so-perfect DTB, especially if this DTB can later be upgraded via different mechanism, like fwupd

2024-08-19 17:24 UTC, quic-vkraleti commented
> @ricardosalveti can we flash a single DTB and ignore selection completely?

AFAIK, even if a single DTB is flashed, board-id check would still happen. Only way to avoid this check is by placing dtb inside UKI.

2024-08-19 17:47 UTC, lumag commented
Oh, my. It would be really nice if such checks were skipped if there is just a single DTB. I think in the past we had to patch ABL to disable such checks.

2024-08-19 17:50 UTC, ricardosalveti commented
We had discussions to allow:
* dtb partition with a series of device tree files, selected via board-id (mostly used by downstream)
* firmware dtb that from linux upstream (that can be updated with the firmware)
* supporting OS-provided dtb via grub/systemd-boot/UKI

But that firmware is still to be release iirc.

2024-08-19 17:51 UTC, ricardosalveti commented
> We had discussions to allow:
> 
> * dtb partition with a series of device tree files, selected via board-id (mostly used by downstream)
> * firmware dtb that from linux upstream (that can be updated with the firmware, used when dtb partition is empty)
> * supporting OS-provided dtb via grub/systemd-boot/UKI
> 
> But that firmware is still to be release iirc.

2024-08-19 17:58 UTC, lumag commented
Well, from my POV the best option is a separate partition with a single DTB file, loaded by the firmware. Then we have a sane default, users can manually change it, fwupd can handle updates.
And if at some point there is a need to go to multiple files, UEFI can use compat strings to make a selection. The board-id will never fly and will never be accepted upstream as a generic solution. In the mobile world nearly every phone vendor mishandles those options, telling that the phone is MTP (or QRD).

Of course grub/systemdboot still can override the loaded DTB if it is specified in the config.

2024-08-19 18:20 UTC, ricardosalveti commented
> Well, from my POV the best option is a separate partition with a single DTB file, loaded by the firmware. Then we have a sane default, users can manually change it, fwupd can handle updates.

That is indeed a goal, but need to check on the details there as the name (and possibly board-id) needs to match what is expected by the firmware.

2024-08-19 18:38 UTC, lumag commented
Name -- agreed, but isn't firmware already loading a combined DTB file? We can use that file name.
Board-id -- make firmware ignore it if there is a single entry. Or maybe make a special case for something like `default.dtb`.

2024-08-20 17:18 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +SRC_URI = ""
Removed for now. Will share a separate PR with clear description of issue I was facing.

2024-08-20 17:19 UTC, quic-vkraleti commented on recipes-kernel/images/dtb-qcom-image.bb
> +
I tired my best in latest commit. Please feel free to reword as appropriate.

2024-08-20 21:18 UTC, ricardosalveti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +    rm -f ${B}/combined-dtb.dtb
This is probably not needed, and if you need a custom B folder you can extend do_compile[cleandirs] with it.

2024-08-20 21:18 UTC, ricardosalveti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +      echo "combining: $kdtb"
First line has 4 spaces and the additional lines just 2 for indentation, align everything with 4 spaces instead.

2024-08-20 21:23 UTC, ricardosalveti commented on recipes-kernel/images/linux-qcom-uki.bb
> +        output="${B}${EFI_UKI_PATH}/${PN}-$(basename "$kdtb" .dtb)-${MACHINE}.efi"
While useful this might later explode in a large number of UKIs, based on the device trees available and set by the user. Can't we instead just create one with the defined dtb from the user (and empty if not set by the user)?

2024-08-20 21:24 UTC, ricardosalveti commented on recipes-kernel/images/linux-qcom-uki.bb
> +        output="${B}${EFI_UKI_PATH}/${PN}-$(basename "$kdtb" .dtb)-${MACHINE}.efi"
Mostly concerned about size issues, as UKI will contain kernel + initrd + dtb for every dtb available in the list.

2024-08-21 04:10 UTC, lumag commented on recipes-kernel/images/dtb-qcom-image.bb
> +
You have described UEFI behavior rather than the package itself. Please describe what the package does.

2024-08-21 04:13 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    [ -f $kernel_image ] && echo "Creating UKI with $kernel_image"
Why is this commit necessary at all? Why do you need to override the DTB? Commit message should answer such questions. In general, commit messages should respond to the ’why?’ question instead of simply describing what is being done (which is usually obvious from the commit itself).

2024-08-21 04:17 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> +    ${EFI_LINUX_IMG} \
Same comment. Commit message doesn't describe the reason for a change. Default DTB should be fine, otherwise there is little point in it.

2024-08-21 04:20 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +    rm -f ${B}/combined-dtb.dtb
I think it is fine, this can save us from possible issues if the task or the script gets executed manually.

2024-08-21 16:05 UTC, quic-vkraleti commented
@lumag @ricardosalveti I dropped two commits for enhancing uki to accept optional DTB from this PR. I'll submit another PR for those in some time.

2024-08-22 01:12 UTC, lumag commented
- package description is still incorrect
- DTB selection is based on the non-standard property 
- commit message describes `board-id`, while the actual property is `qcom,board-id`

2024-08-22 02:34 UTC, ricardosalveti commented
> * package description is still incorrect

The description was updated with "This recipe creates a vfat image with the 'combined-dtb.dtb' for UEFI consumption.", which is the intent.

> * DTB selection is based on the non-standard property

While not ideal, this is the current firmware behavior and will probably stay this way until an upstream compatible solution is found (discussion in progress). Not something that can be changed as part of this PR.

2024-08-22 02:39 UTC, lumag commented
Ack for the description. 
For the DTB, can we pretty please have a single DTB with no additional selection. There is no reason to install several different revisions if we know in advance, which one is going to be selected.

2024-08-22 02:43 UTC, ricardosalveti commented
> Ack for the description. For the DTB, can we pretty please have a single DTB with no additional selection. There is no reason to install several different revisions if we know in advance, which one is going to be selected.

This feature will be supported in a newer firmware release, currently in development. Once available we can update the logic here.

2024-08-22 02:44 UTC, lumag commented
I'm reluctant to merge a solution that depends on the patches that are not going to bed accepted upstream. And [upstream DT](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/boot/dts/qcom/qcs6490-rb3gen2.dts?h=v6.11-rc4) has neither `qcom, msm-id` nor `qcom,board-id` properties.

2024-08-29 09:54 UTC, lumag commented on conf/machine/include/qcom-common.inc
> +    "
Why can't we pack all KERNEL_DEVICETREE ?

2024-08-29 09:57 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +    fi
The more I look at this recipe the more I think that it's better turn into a bbclass to be used by kernel recipes. Then we can use `KERNEL_DEVICETREE` even if it get overriden for the kernel recipe and/or version. And the combined-dtb will be automatically repopulated if the kernel image changes.

2024-08-29 09:59 UTC, lumag requested changes

2024-08-29 09:59 UTC, lumag commented on recipes-kernel/images/dtb-qcom-image.bb
> +
Still not resolved.

2024-08-29 10:24 UTC, quic-vkraleti reviewed
Qualcomm is exploring the suggestion to use FIT format based approach to pick a DTB so that it gets upstream aligned. Present dependency on qcom,board-id would be dropped with in an year time frame.

2024-08-29 10:24 UTC, quic-vkraleti commented on recipes-kernel/images/dtb-qcom-image.bb
> +
"This recipe creates a vfat image with 'combined-dtb.dtb' for UEFI consumption." isn't it appropriate?

2024-08-29 10:24 UTC, quic-vkraleti commented on conf/machine/include/qcom-common.inc
> +    "
dtbs are enabled based on the recipe provider of virtual/kernel. If dtb enablement happens in a generic way, KERNEL_DEVICETREE can be parsed to get dtbs. Till then this list has to be maintained. As discussed over telcon UEFI firmware is being enhanced to stop reading board-id if there is a single dtb. Packing all of  KERNEL_DEVICETREE would mean the qcom,board-id based checks still need to be maintained.

2024-08-29 10:24 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +    fi
Sure, will consider for next PR.

2024-08-29 10:28 UTC, lumag commented on recipes-kernel/images/dtb-qcom-image.bb
> +
Please describe the package and not the recipe.

2024-08-29 10:29 UTC, lumag commented on recipes-kernel/images/linux-qcom-combinedtb.bb
> +               binary blob that can be provided to the UEFI."
Please describe the package a not the recipe.

```
DESCRIPTION[doc] = "The package description used by package managers. If not set, DESCRIPTION takes the value of the SUMMARY variable."
```

2024-08-29 10:32 UTC, lumag commented on conf/machine/include/qcom-common.inc
> +    "
In such a case you can just create one image per DTB. From the bbclass iterate over the `KERNEL_DEVICETREE` and call `mkfs.vfat` manually for each DTB.

2024-08-29 11:01 UTC, quic-vkraleti commented on conf/machine/include/qcom-common.inc
> +    "
Sure, I'll drop linux-qcom-combineddtb recipe and add a kernel bbclass to generate one vfat image per DTB.

2024-09-05 08:50 UTC, quic-vkraleti commented on conf/machine/include/qcom-common.inc
> +    "
Done, added a bbclass to create a dtb image for each dtb produced by kernel.

2024-09-05 10:04 UTC, lumag requested changes
Looks great now, let's fix two minor issues.

2024-09-05 10:04 UTC, lumag commented on classes/linux-qcom-dtbbin.bbclass
> +DTBBIN_SIZE ?= "65536"
I think 64M is a bit too big for a DTB partition. What about getting that down to 2M or 4M? If we need more, we can expand it later.

2024-09-05 10:04 UTC, lumag commented on classes/linux-qcom-dtbbin.bbclass
> +        mkfs.vfat $@ -C ${DTBBIN_DEPLOYDIR}/combined-dtb-$dtb_base_name.vfat ${DTBBIN_SIZE}
What about `dtb-${dtb_base_name}-image.vfat` ? This way it's not specific to the `combined/etc.` logic. And if the logic or partition internals change, the user won't have to look for a new name.

2024-09-05 10:21 UTC, quic-vkraleti commented on classes/linux-qcom-dtbbin.bbclass
> +        mkfs.vfat $@ -C ${DTBBIN_DEPLOYDIR}/combined-dtb-$dtb_base_name.vfat ${DTBBIN_SIZE}
Sure, I'll update.

2024-09-05 10:33 UTC, quic-vkraleti commented on classes/linux-qcom-dtbbin.bbclass
> +DTBBIN_SIZE ?= "65536"
reduced to 4MB.

2024-09-05 10:35 UTC, lumag approved these changes

2024-09-05 10:35 UTC, lumag commented
LGTM now

2024-09-06 00:37 UTC, ricardosalveti approved these changes
LGTM

2024-09-06 00:38 UTC, merged