Support optional dtb loading via UKI
Linaro/meta-qcom pull request #622
Opened 2024-08-21 16:51 UTC by quic-vkraleti

If a DTB is present in UKI, systemd-boot can override the default UEFI provided DTB. This provisioning of DTB via UKI allows the users to customize DTBs as per product needs without regenerating the firmware.

2024-08-21 19:21 UTC, lumag requested changes

2024-08-21 19:21 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    [ -f $kernel_image ] && echo "Creating UKI with $kernel_image"
Why? Commit message provides no reason to drop this bbfatal.

2024-08-21 19:21 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    dtb="${DEPLOY_DIR_IMAGE}/${EFI_LINUX_IMG_DTB}"
Please, drop extra empty line

2024-08-21 19:21 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +        bbdebug 1 "$dtb is not valid dtb to create UKI."
`[ -r $dtb ] || bbfatal dtbs not found`

2024-08-21 19:21 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
If this commit depends on the boot flow changes, then it should be a part of #620

2024-08-21 19:42 UTC, ricardosalveti commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
It doesn't depend on the combined dtb logic, since what is basically happening here is moving the dtb from esp to be part of UKI.

2024-08-21 19:43 UTC, ricardosalveti commented on recipes-kernel/images/linux-qcom-uki.bb
> +    [ -f $kernel_image ] && echo "Creating UKI with $kernel_image"
Yeah, without kernel image we should still fail as before, right?

2024-08-21 19:45 UTC, ricardosalveti commented on recipes-kernel/images/linux-qcom-uki.bb
> +        bbdebug 1 "$dtb is not valid dtb to create UKI."
For it to be fatal we need to always define a default for EFI_LINUX_IMG_DTB (which we should probably do anyway, like using the first dtb available in KERNEL_DEVICETREE or similar, with a weak assignment.

2024-08-22 00:51 UTC, quic-vkraleti commented on recipes-kernel/images/linux-qcom-uki.bb
> +    [ -f $kernel_image ] && echo "Creating UKI with $kernel_image"
SKIP_RECIPE check is present at end of the file to check for 'Image' in kernel image types. This condition is not needed any more.

2024-08-22 00:53 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    [ -f $kernel_image ] && echo "Creating UKI with $kernel_image"
Unrelated change ergo separate commit with its own justification.

2024-08-22 00:55 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +        bbdebug 1 "$dtb is not valid dtb to create UKI."
Not quite. Empty EFI_LINUX_IMG_DTB should be a separate condition. And also there default should be empty string, i.e. use DTB provided by the firmware.

2024-08-22 00:57 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +    dtb="${DEPLOY_DIR_IMAGE}/${EFI_LINUX_IMG_DTB}"
Argh, it's just a GitHub on a cell phone, there is no empty line. Please ignore the comment.

2024-08-22 00:59 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
No, it is not a move. This PR provides a way to override the DTB provided by the firmware.

2024-08-22 02:37 UTC, ricardosalveti commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
The latest firmware is not loading from the esp partition anymore, but from combined-dtb. With latest firmware at least the dtb files from esp would only really be useful to the OS, and a similar behavior is applied with UKIs here.

2024-08-22 02:41 UTC, ricardosalveti commented on recipes-kernel/images/linux-qcom-uki.bb
> +        bbdebug 1 "$dtb is not valid dtb to create UKI."
Right, my thinking is that we could have 2 variables, one to control if the dtb should be added to UKI and the other with the dtb string to be used, which can be set to the first one by default (with weak assignment).

2024-08-22 02:47 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +        bbdebug 1 "$dtb is not valid dtb to create UKI."
No, weak assignment is really incorrect. The first DTB is the one for db410c if I'm not mistaken.

2024-08-22 02:50 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
So... If anybody has DTB in ESP, they can get unbootable device by updating the firmware? That's ridiculous.

2024-08-22 02:52 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
I'm currently OOO. Could you please schedule a telco on Monday or Tuesday, let's discuss what is going on and what we can do.

2024-08-22 02:56 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
Please also invite @calebccff

2024-08-22 02:56 UTC, ricardosalveti commented on recipes-kernel/images/linux-qcom-uki.bb
> +        bbdebug 1 "$dtb is not valid dtb to create UKI."
Right, for a generic target/config this won't really be useful due the amount of dtbs used.

2024-08-22 02:59 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +        bbdebug 1 "$dtb is not valid dtb to create UKI."
Yep. So if for some stranger reason somebody has a single-machine config, it makes sense to have that variable assigned in the machine config. But it's not sensible to set it in generic config.

2024-08-22 03:07 UTC, lumag commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
I'd suggest having a recipe that generates a set of DTB-vfat images with a single DTB in each. This is going to work with the current approach and it will continue to work once FW gets updated to ignore custom properties.

2024-08-22 03:20 UTC, ricardosalveti commented on recipes-kernel/images/esp-qcom-image.bb
> -    kernel-devicetree \
Will sync internally first to understand the previous boot firmware expectations here, I'm just familiar with what the latest version is currently doing.

2024-08-30 17:58 UTC, lumag requested changes
Please make it a fatal error if the user specifies non-empty EFI_LINUX_IMG_DTB, but the `$dtb` doesn't exist. Other than that looks good.

2024-09-05 10:06 UTC, lumag commented on recipes-kernel/images/linux-qcom-uki.bb
> +        bbdebug 1 "$dtb is not valid dtb to create UKI."
I'd really like to merge this. I think the `bbfatal` is the only comment that still needs attention.

2024-09-05 10:17 UTC, lumag approved these changes

2024-09-05 11:00 UTC, merged