meta-qcom: initial u-boot support
Linaro/meta-qcom pull request #651
Opened 2024-09-13 19:11 UTC by Scott31393

Hi,

This patchset add the initial support for u-boot-qcom.
This has been tested on rb3gen2 board:

Flashing the image using fastboot:
```
fastboot flash uefi_a ./u-boot-qcs6490-rb3gen2.mbn
```

Below some logs from the test.
```
U-Boot 2024.10-rc4-00620-ga61af132fb90 (Sep 09 2024 - 10:00:06 +0000)

Model: Qualcomm Technologies, Inc. Robotics RB3gen2
DRAM:  6 GiB (effective 5.9 GiB)
serial_msm_geni serial@994000: pinctrl_select_state_full: uclass_get_device_by_phandle_id: err=-19
serial_msm_geni serial@994000: pinctrl_select_state_full: uclass_get_device_by_phandle_id: err=-19
Core:  57 devices, 28 uclasses, devicetree: board

Loading Environment from nowhere... OK
In:    serial,button-kbd
Out:   serial,vidconsole
Err:   serial,vidconsole
qcom-ufshcd ufs@1d84000: Qcom UFS HC version: 4.3.0
qcom-ufshcd ufs@1d84000: [RX, TX]: gear=[3, 3], lane[2, 2], pwr[FAST MODE, FAST MODE], rate = 2
QCOM-FMP: Failed to find boot partition
Net:   No ethernet found.

scanning bus for devices...
  Device 0: (0:0) Vendor: SAMSUNG Prod.: KM2L9001CM-B518 Rev: 0700
            Type: Hard Disk
            Capacity: 118871.9 MB = 116.0 GB (30431231 x 4096)
  Device 1: (0:1) Vendor: SAMSUNG Prod.: KM2L9001CM-B518 Rev: 0700
            Type: Hard Disk
            Capacity: 7.9 MB = 0.0 GB (2047 x 4096)
  Device 2: (0:2) Vendor: SAMSUNG Prod.: KM2L9001CM-B518 Rev: 0700
            Type: Hard Disk
            Capacity: 7.9 MB = 0.0 GB (2047 x 4096)
  Device 3: (0:3) Vendor: SAMSUNG Prod.: KM2L9001CM-B518 Rev: 0700
            Type: Hard Disk
            Capacity: 31.9 MB = 0.0 GB (8191 x 4096)
  Device 4: (0:4) Vendor: SAMSUNG Prod.: KM2L9001CM-B518 Rev: 0700
            Type: Hard Disk
            Capacity: 3071.9 MB = 2.9 GB (786431 x 4096)
  Device 5: (0:5) Vendor: SAMSUNG Prod.: KM2L9001CM-B518 Rev: 0700
            Type: Hard Disk
            Capacity: 31.9 MB = 0.0 GB (8191 x 4096)
starting USB...
Bus usb@a600000: Register 2000340 NbrPorts 2
Starting the controller
USB XHCI 1.10
scanning bus usb@a600000 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
=> <INTERRUPT>
```

Thanks & Regards,
Tommaso

2024-09-13 20:59 UTC, ricardosalveti commented on recipes-devtools/qtestsign/qtestsign.bb
> +HOMEPAGE = "https://github.com/msm8916-mainline/qtestsign?tab=readme-ov-file"
Use just 'https://github.com/msm8916-mainline/qtestsign'.

2024-09-13 20:59 UTC, ricardosalveti commented on recipes-devtools/qtestsign/qtestsign.bb
> +LIC_FILES_CHKSUM = "file://README.md;md5=9e567e101dbb0b57bc860e97460381f8"
https://github.com/msm8916-mainline/qtestsign/blob/main/COPYING is a better file to track, license can change often on repo updates.

2024-09-13 21:01 UTC, ricardosalveti commented on recipes-devtools/qtestsign/qtestsign.bb
> +DEPENDS = "python3"
I don't think it requires anything from python3, you're just installing the files directly.

2024-09-13 21:02 UTC, ricardosalveti commented on recipes-devtools/qtestsign/qtestsign.bb
> +inherit python3native
Python native is also not really used here.

2024-09-13 21:03 UTC, ricardosalveti commented on recipes-devtools/qtestsign/qtestsign.bb
> +do_install() {
Install should use the traditional ${D} folders, as you will also want to generate packages that could potentially be used by the target.

If you need to deploy (which might not really be needed), then use do_deploy instead.

2024-09-13 21:03 UTC, ricardosalveti commented on recipes-devtools/qtestsign/qtestsign.bb
> +SUMMARY = "qtestsign is a simple tool to sign ELF Qualcomm firmware images"
Have recipe with _git.bb to indicate the version as well.

2024-09-13 21:07 UTC, ricardosalveti commented on recipes-bsp/u-boot/u-boot-qcom.bb
> +    xxd-native bc-native dtc-native qtestsign\
You will want a qtestsign-native instead, and run qtestsign from staging.

2024-09-13 21:08 UTC, ricardosalveti commented on recipes-bsp/u-boot/u-boot-qcom.bb
> +    cp -r ${B}/qcm6490_defconfig/u-boot.elf ${DEPLOY_DIR_IMAGE}/u-boot-qcs6490-rb3gen2.elf
Better to sign as part of compile and then deploy the signed file instead.

2024-09-13 21:10 UTC, ricardosalveti commented on recipes-bsp/u-boot/u-boot-qcom.bb
> +require recipes-bsp/u-boot/u-boot.inc
If a u-boot fork is indeed required, also indicate the base version, as done by most u-boot forks (e.g. u-boot-fslc_2024.04,  etc).

2024-09-13 21:10 UTC, ricardosalveti commented on recipes-bsp/u-boot/u-boot-qcom-common.inc
> +SRCREV = "${AUTOREV}"
Better to use a fixed rev instead, autorev is useful for local dev instead.

2024-09-13 22:02 UTC, Scott31393 commented on recipes-devtools/qtestsign/qtestsign.bb
> +HOMEPAGE = "https://github.com/msm8916-mainline/qtestsign?tab=readme-ov-file"
Thanks will post v2.

2024-09-13 22:03 UTC, Scott31393 commented on recipes-devtools/qtestsign/qtestsign.bb
> +LIC_FILES_CHKSUM = "file://README.md;md5=9e567e101dbb0b57bc860e97460381f8"
Oks will post v2.

2024-09-13 22:35 UTC, Scott31393 commented on recipes-devtools/qtestsign/qtestsign.bb
> +inherit python3native
Hi Ricardo,

Thanks for your comments.
inherit python3native is required in ordere to use: 

```
${PYTHON_SITEPACKAGES_DIR}
```
variable

2024-09-13 22:38 UTC, Scott31393 commented on recipes-devtools/qtestsign/qtestsign.bb
> +SUMMARY = "qtestsign is a simple tool to sign ELF Qualcomm firmware images"
Hi Ricardo,
Thanks for your comment.

Version ce6ba20f4ead008e5b522a81179c98dd48ccf06e is?
Can't see any tags into the repo :'(

Thanks & Regards,
Tommaso

2024-09-13 22:47 UTC, ricardosalveti commented on recipes-devtools/qtestsign/qtestsign.bb
> +SUMMARY = "qtestsign is a simple tool to sign ELF Qualcomm firmware images"
you can just name the recipe as qtestsign_git.bb

2024-09-13 23:08 UTC, Scott31393 commented on recipes-devtools/qtestsign/qtestsign.bb
> +SUMMARY = "qtestsign is a simple tool to sign ELF Qualcomm firmware images"
Perfect, thanks.

2024-09-13 23:16 UTC, Scott31393 commented on recipes-bsp/u-boot/u-boot-qcom-common.inc
> +SRCREV = "${AUTOREV}"
Are we sure?
u-boot on rb3gen2 it's pretty new and I saw a lot of commits during the past weeks?

I will post v2 with this and the upper comment not solved for now. (need to sleep :) )
Here in Italy it's like 1.15 am :)

Let me know.
Will continue during the next days. (thanks for the review)

2024-09-13 23:19 UTC, ricardosalveti commented on recipes-bsp/u-boot/u-boot-qcom-common.inc
> +SRCREV = "${AUTOREV}"
Better because otherwise anyone building might get a different result (possibly build failures as well) based on how the upstream repo changes. Since it is also ideal to add this recipe as part of the CI build loop, better to have something that is reproducible.

Anyone can propose rev changes when needed, based on how the upstream project / repo evolves.

2024-09-14 14:39 UTC, lumag commented
@calebccff, could you please take a look/

2024-09-14 16:13 UTC, calebccff commented on conf/machine/qcom-armv8a.conf
> +UBOOT_CONFIG[sdm845-db845c] = "qcom_defconfig"
you don't seem to do anything with this, should this sort rb3 as well?

2024-09-14 16:15 UTC, calebccff commented on recipes-bsp/u-boot/u-boot-qcom_2024.10.bb
> +    ${QTESTSIGN} -v6 hyp -o ${B}/qcm6490_defconfig/u-boot.mbn ${B}/qcm6490_defconfig/u-boot.elf
i think this should be sbl1 rather than hyp?

2024-09-14 16:17 UTC, calebccff commented
overall looks pretty good! excited to see this support being added :D

2024-09-14 17:05 UTC, Scott31393 commented
Thanks for your work! :)

2024-09-16 11:30 UTC, quaresmajose commented on recipes-devtools/qtestsign/qtestsign_git.bb
> +}
There are some files installed which are not necessary so they can be deleted
```
    cd ${D}${PYTHON_SITEPACKAGES_DIR}/qtestsign
    cp -r ${S}/* .
    rm README.md COPYING requirements.txt
```
Create a symbolic link on the default path will be good 
```    
    # make it available on the default path
    install -d ${D}${bindir}
    ln -s ${PYTHON_SITEPACKAGES_DIR}/qtestsign/qtestsign.py ${D}${bindir}/qtestsign
```

2024-09-16 11:30 UTC, quaresmajose commented on recipes-bsp/u-boot/u-boot-qcom_2024.10.bb
> +QTESTSIGN = "${STAGING_LIBDIR_NATIVE}/${PYTHON_DIR}/site-packages/qtestsign/qtestsign.py"
with the symbolic link, the `QTESTSIGN` is not needed and it can be called directly with `qtestsign`

2024-09-17 19:31 UTC, lumag commented on recipes-bsp/u-boot/u-boot-qcom-common.inc
> +SRCREV = "${AUTOREV}"
Generally it's recommended to use a fixed revision, so that it is possible to build images with no network access. Please only use AUTOREV if it was explicitly required by the user. Few examples:

```
SRCREV := "${@oe.utils.conditional("MESA_DEV", "1", "${AUTOREV}", "26677008b9a7c0ef82f2a7f4b479d3cb06097c66", d)}"
-SRCREV := '${@oe.utils.conditional("PREFERRED_PROVIDER_virtual/kernel", "linux-linaro-qcomlt-dev", "${AUTOREV}", "29594404d7fe73cd80eaa4ee8c43dcc53970c60e", d)}'
```

Another option is to use `class-devupstream` and then `SRCREV:class-devupstream = "${AUTOREV}"`.

2024-09-17 19:35 UTC, lumag commented on recipes-bsp/u-boot/u-boot-qcom_2024.10.bb
> +    python3-cryptography-native \
I think these python packages are required for `qtestsign` invocation. Please move them to `RDEPENDS` in the `qtestign` recipe.

2024-09-17 19:39 UTC, lumag commented on recipes-bsp/u-boot/u-boot-qcom_2024.10.bb
> +version, or because it is not applicable for upstreaming."
```
SECTION = "bootloaders"
```

Also, I see that `u-boot-common.inc` inherits `pkgconfig`. Is it necessary only for some configs (which don't include qcom)?

2024-09-17 19:41 UTC, lumag commented on recipes-bsp/u-boot/u-boot-qcom_2024.10.bb
> +    cp -r ${B}/qcm6490_defconfig/u-boot.mbn ${DEPLOY_DIR_IMAGE}/u-boot-qcs6490-rb3gen2.mbn
Please deploy both signed binary (as a default name) and an unsigned one.

2024-09-19 09:10 UTC, lumag commented on recipes-bsp/u-boot/u-boot-qcom_git.bb
> +    python3-cryptography-native \
Why do we need these -native packages here? They should be pulled through qtestsign-native.

2024-09-19 09:11 UTC, lumag commented on recipes-bsp/u-boot/u-boot-qcom_git.bb
> +QTESTSIGN = "${STAGING_LIBDIR_NATIVE}/${PYTHON_DIR}/site-packages/qtestsign/qtestsign.py"
I think I saw a comment asking to install qtestsign into a native bindir, then calling it directly rather than via the raw path. That still applies.

2024-09-19 09:12 UTC, lumag commented on recipes-bsp/u-boot/u-boot-qcom_git.bb
> +    cp -r ${B}/qcm6490_defconfig/u-boot.mbn ${DEPLOY_DIR_IMAGE}/u-boot-qcs6490-rb3gen2.mbn
I asked to deploy both signed and unsigned binaries

2024-09-19 09:16 UTC, quaresmajose commented on recipes-bsp/u-boot/u-boot-qcom_git.bb
> +    python3-cryptography-native \
+1 we not need the python3-cryptography-native there

2024-09-19 09:18 UTC, quaresmajose commented on recipes-bsp/u-boot/u-boot-qcom_git.bb
> +QTESTSIGN = "${STAGING_LIBDIR_NATIVE}/${PYTHON_DIR}/site-packages/qtestsign/qtestsign.py"
right, we not need this QTESTSIGN if the qtestsign found on the default PATH

2024-09-19 12:20 UTC, lumag requested changes

2024-09-19 12:20 UTC, lumag commented on recipes-bsp/u-boot/u-boot-qcom_git.bb
> +    cp -r ${B}/qcm6490_defconfig/u-boot.mbn ${DEPLOY_DIR_IMAGE}/u-boot-qcs6490-rb3gen2.mbn
Almost missed this, excuse me. You are not supposed to write to `${DEPLOY_DIR_IMAGE}`. This directory doesn't get included into sstate. So, restoring the boot from the sstate would result in the images being missing. Please change your code to deploy images to `${DEPLOYDIR}` instead.

2024-09-19 14:26 UTC, quaresmajose commented on recipes-devtools/qtestsign/qtestsign_git.bb
> +
@Scott31393 also noted that this is still missing

2024-09-19 16:41 UTC, calebccff commented on recipes-bsp/u-boot/u-boot-qcom_2024.10.bb
> +    ${QTESTSIGN} -v6 hyp -o ${B}/qcm6490_defconfig/u-boot.mbn ${B}/qcm6490_defconfig/u-boot.elf
Yep this should be aboot, that's what I've been doing locally.

2024-09-19 16:42 UTC, calebccff commented on conf/machine/qcom-armv8a.conf
> +UBOOT_CONFIG[sdm845-db845c] = "qcom_defconfig"
fixed my typo, meant to ask if db845c should be included here or not since I don't see support for generating a boot image or building a modified xbl image.

2024-09-20 07:34 UTC, lumag commented on recipes-devtools/qtestsign/qtestsign_git.bb
> +
I think it's fine. Other python recipes don't inhibit dependencies.

2024-09-20 07:37 UTC, lumag approved these changes

2024-09-20 10:05 UTC, quaresmajose commented on recipes-devtools/qtestsign/qtestsign_git.bb
> +
The INHIBIT_DEFAULT_DEPS is not critical and its omission does not break any recipe, the opposite is not true.
It is mostly for speeding up bitbake not pulling pieces on the native sysroot we don't need.

2024-09-20 10:06 UTC, quaresmajose approved these changes
Thanks @Scott31393 
LGTM

2024-09-20 10:16 UTC, merged

2024-09-20 10:16 UTC, lumag commented
@Scott31393 thank you for your contribution and for your patience through the review process!

2024-09-20 11:56 UTC, Scott31393 commented
Hi @lumag nice!
Nothing to thanks!

@quaresmajose Thanks you all for the reviews and comments.
@calebccff Can't wait to see eth support at u-boot level and weston.

If I have some time I will try to take look on that into the next months ;)

2024-09-20 12:11 UTC, calebccff commented
> @calebccff Can't wait to see eth support at u-boot level and weston.
> 
> If I have some time I will try to take look on that into the next months ;)

ethernet works nicely on the rb1/2/5, its unfortunate that the rb3 and rb3gen2 use pcie hubs, but I'm working on it :p

2024-09-20 13:25 UTC, Scott31393 commented
> > @calebccff Can't wait to see eth support at u-boot level and weston.
> > If I have some time I will try to take look on that into the next months ;)
> 
> ethernet works nicely on the rb1/2/5, its unfortunate that the rb3 and rb3gen2 use pcie hubs, but I'm working on it :p

Nice! Thanks for your work
pcie2usb :) Can't wait ;) I will try to take a look also on my side.
nfs + tftp :Q____